export type LivreBible = { code: string; nom: string; testament: 'AT' | 'NT'; nbVersets: number }

export const LIVRES: LivreBible[] = [
  { code: 'GEN', nom: 'Genèse',                   testament: 'AT', nbVersets: 1533 },
  { code: 'EXO', nom: 'Exode',                    testament: 'AT', nbVersets: 1213 },
  { code: 'LEV', nom: 'Lévitique',                testament: 'AT', nbVersets:  859 },
  { code: 'NUM', nom: 'Nombres',                  testament: 'AT', nbVersets: 1288 },
  { code: 'DEU', nom: 'Deutéronome',              testament: 'AT', nbVersets:  959 },
  { code: 'JOS', nom: 'Josué',                    testament: 'AT', nbVersets:  658 },
  { code: 'JDG', nom: 'Juges',                    testament: 'AT', nbVersets:  618 },
  { code: 'RUT', nom: 'Ruth',                     testament: 'AT', nbVersets:   85 },
  { code: '1SA', nom: '1 Samuel',                 testament: 'AT', nbVersets:  810 },
  { code: '2SA', nom: '2 Samuel',                 testament: 'AT', nbVersets:  695 },
  { code: '1KI', nom: '1 Rois',                   testament: 'AT', nbVersets:  816 },
  { code: '2KI', nom: '2 Rois',                   testament: 'AT', nbVersets:  719 },
  { code: '1CH', nom: '1 Chroniques',             testament: 'AT', nbVersets:  942 },
  { code: '2CH', nom: '2 Chroniques',             testament: 'AT', nbVersets:  822 },
  { code: 'EZR', nom: 'Esdras',                   testament: 'AT', nbVersets:  280 },
  { code: 'NEH', nom: 'Néhémie',                  testament: 'AT', nbVersets:  406 },
  { code: 'EST', nom: 'Esther',                   testament: 'AT', nbVersets:  167 },
  { code: 'JOB', nom: 'Job',                      testament: 'AT', nbVersets: 1070 },
  { code: 'PSA', nom: 'Psaumes',                  testament: 'AT', nbVersets: 2461 },
  { code: 'PRO', nom: 'Proverbes',                testament: 'AT', nbVersets:  915 },
  { code: 'ECC', nom: 'Ecclésiaste ou Qohélet',  testament: 'AT', nbVersets:  222 },
  { code: 'SNG', nom: 'Cantique des cantiques',   testament: 'AT', nbVersets:  117 },
  { code: 'ISA', nom: 'Isaïe',                    testament: 'AT', nbVersets: 1292 },
  { code: 'JER', nom: 'Jérémie',                  testament: 'AT', nbVersets: 1364 },
  { code: 'LAM', nom: 'Lamentations',             testament: 'AT', nbVersets:  154 },
  { code: 'EZK', nom: 'Ézéchiel',                 testament: 'AT', nbVersets: 1273 },
  { code: 'DAN', nom: 'Daniel',                   testament: 'AT', nbVersets:  357 },
  { code: 'HOS', nom: 'Osée',                     testament: 'AT', nbVersets:  197 },
  { code: 'JOL', nom: 'Joël',                     testament: 'AT', nbVersets:   73 },
  { code: 'AMO', nom: 'Amos',                     testament: 'AT', nbVersets:  146 },
  { code: 'OBA', nom: 'Abdias',                   testament: 'AT', nbVersets:   21 },
  { code: 'JON', nom: 'Jonas',                    testament: 'AT', nbVersets:   48 },
  { code: 'MIC', nom: 'Michée',                   testament: 'AT', nbVersets:  105 },
  { code: 'NAM', nom: 'Nahum',                    testament: 'AT', nbVersets:   47 },
  { code: 'HAB', nom: 'Habacuc',                  testament: 'AT', nbVersets:   56 },
  { code: 'ZEP', nom: 'Sophonie',                 testament: 'AT', nbVersets:   53 },
  { code: 'HAG', nom: 'Aggée',                    testament: 'AT', nbVersets:   38 },
  { code: 'ZEC', nom: 'Zacharie',                 testament: 'AT', nbVersets:  211 },
  { code: 'MAL', nom: 'Malachie',                 testament: 'AT', nbVersets:   55 },
  { code: 'MAT', nom: 'Matthieu',                 testament: 'NT', nbVersets: 1071 },
  { code: 'MRK', nom: 'Marc',                     testament: 'NT', nbVersets:  678 },
  { code: 'LUK', nom: 'Luc',                      testament: 'NT', nbVersets: 1151 },
  { code: 'JHN', nom: 'Jean',                     testament: 'NT', nbVersets:  879 },
  { code: 'ACT', nom: 'Actes',                    testament: 'NT', nbVersets: 1007 },
  { code: 'ROM', nom: 'Romains',                  testament: 'NT', nbVersets:  433 },
  { code: '1CO', nom: '1 Corinthiens',            testament: 'NT', nbVersets:  437 },
  { code: '2CO', nom: '2 Corinthiens',            testament: 'NT', nbVersets:  257 },
  { code: 'GAL', nom: 'Galates',                  testament: 'NT', nbVersets:  149 },
  { code: 'EPH', nom: 'Éphésiens',                testament: 'NT', nbVersets:  155 },
  { code: 'PHP', nom: 'Philippiens',              testament: 'NT', nbVersets:  104 },
  { code: 'COL', nom: 'Colossiens',               testament: 'NT', nbVersets:   95 },
  { code: '1TH', nom: '1 Thessaloniciens',        testament: 'NT', nbVersets:   89 },
  { code: '2TH', nom: '2 Thessaloniciens',        testament: 'NT', nbVersets:   47 },
  { code: '1TI', nom: '1 Timothée',               testament: 'NT', nbVersets:  113 },
  { code: '2TI', nom: '2 Timothée',               testament: 'NT', nbVersets:   83 },
  { code: 'TIT', nom: 'Tite',                     testament: 'NT', nbVersets:   46 },
  { code: 'PHM', nom: 'Philémon',                 testament: 'NT', nbVersets:   25 },
  { code: 'HEB', nom: 'Hébreux',                  testament: 'NT', nbVersets:  303 },
  { code: 'JAS', nom: 'Jacques',                  testament: 'NT', nbVersets:  108 },
  { code: '1PE', nom: '1 Pierre',                 testament: 'NT', nbVersets:  105 },
  { code: '2PE', nom: '2 Pierre',                 testament: 'NT', nbVersets:   61 },
  { code: '1JN', nom: '1 Jean',                   testament: 'NT', nbVersets:  105 },
  { code: '2JN', nom: '2 Jean',                   testament: 'NT', nbVersets:   13 },
  { code: '3JN', nom: '3 Jean',                   testament: 'NT', nbVersets:   14 },
  { code: 'JUD', nom: 'Jude',                     testament: 'NT', nbVersets:   25 },
  { code: 'REV', nom: 'Apocalypse',               testament: 'NT', nbVersets:  404 },
]

export const ABREV_FR: Record<string, string> = {
  GEN:'Gn',  EXO:'Ex',  LEV:'Lv',  NUM:'Nb',  DEU:'Dt',
  JOS:'Jos', JDG:'Jg',  RUT:'Rt',
  '1SA':'1S','2SA':'2S','1KI':'1R','2KI':'2R',
  '1CH':'1Ch','2CH':'2Ch',
  EZR:'Esd', NEH:'Né',  EST:'Est', JOB:'Jb',  PSA:'Ps',
  PRO:'Pr',  ECC:'Qo',  SNG:'Ct',
  ISA:'Is',  JER:'Jr',  LAM:'Lm',  EZK:'Ez',  DAN:'Dn',
  HOS:'Os',  JOL:'Jl',  AMO:'Am',  OBA:'Ab',  JON:'Jon',
  MIC:'Mi',  NAM:'Na',  HAB:'Ha',  ZEP:'So',  HAG:'Ag',
  ZEC:'Za',  MAL:'Ml',
  MAT:'Mt',  MRK:'Mc',  LUK:'Lc',  JHN:'Jn',  ACT:'Ac',
  ROM:'Rm',
  '1CO':'1Co','2CO':'2Co',
  GAL:'Ga',  EPH:'Ep',  PHP:'Ph',  COL:'Col',
  '1TH':'1Th','2TH':'2Th','1TI':'1Tm','2TI':'2Tm',
  TIT:'Tt',  PHM:'Phm', HEB:'He',  JAS:'Jc',
  '1PE':'1P','2PE':'2P',
  '1JN':'1Jn','2JN':'2Jn','3JN':'3Jn',
  JUD:'Jude',REV:'Ap',
}
