// Livre V — Questions sur le Deutéronome. Pages 537 (s2) - 559 (s1).
export default {
  cle: "deuteronome", fichier: "Deuteronome_draft",
  titre: "Livre cinquième — Questions sur le Deutéronome",
  titreCourt: "Deutéronome",
  de: 537, a: 559, debutSection: "s2", finSection: "s1",
  CORR: [
    // ── p537 ──
    ["(Deutéronome, 1, 29-30.)", "(Deutéronome, I, 29, 30.)"],
    ["(Ib. 2, 30.)", "(Ib. II, 30.)"],
    // ── p538 ──
    ["(Ib. 3, 2.)", "(Ib. III, 2.)"],
    ["roi deBasan", "roi de Basan"],
    ["Raphaïn", "Raphaïm"],
    ["Raphaïm''signifie", "Raphaïm'' signifie"],
    ["(Ib. 4,16.)", "(Ib. IV, 16.)"],
    ["ou ces deux fermes expriment", "ou ces deux termes expriment"],
    ["on ne dirait pas quelle a été faite", "on ne dirait pas qu’elle a été faite"],
    ["du mol ressemblance", "du mot ressemblance"],
    ["(Ib. Ib., 18.)", "(Ib. IV, 18.)"],
    ["Que signifient ces paroles.", "Que signifient ces paroles :"],
    ["les eaux sons la terre", "les eaux sous la terre"],
    ["Le moi terre", "Le mot terre"],
    ["de l’eau eu raison", "de l’eau en raison"],
    // ── p539 ──
    ["(Ib. 4,19.)", "(Ib. IV, 19.)"],
    ["à toutes les « nations", "à toutes les nations"],
    ["(Ib. 4,23.)", "(Ib. IV, 23.)"],
    ["(Ib. 5, 32-33.)", "(Ib. V, 32, 33.)"],
    ["qui ont été avant, vous", "qui ont été avant vous"],
    ["d’un bout de la terre à l’autre La raison", "d’un bout de la terre à l’autre ? La raison"],
    ["(Ib. 5, 2-4.)", "(Ib. V, 2-4.)"],
    ["à eux an milieu des flammes", "à eux au milieu des flammes"],
    // ── p540 ──
    ["qu’est-ce qui empêché de donner", "qu’est-ce qui empêche de donner"],
    ["afin que je vous « voie certainement", "afin que je vous voie certainement"],
    ["quelle en sera ta grandeur", "quelle en sera la grandeur"],
    ["CXXLVII, 36#Rem", "CXLVII, 36#Rem"],
    ["(Ib. 5, 5.)", "(Ib. V, 5.)"],
    ["Moise ne dit donc pas", "Moïse ne dit donc pas"],
    ["et comme il tremblait en entendant la voix de Dieu promulguer le Décalogue, il demanda", ""],
    // ── p541 ──
    ["comme une grâce que Moïse lui servit", "et comme il tremblait en entendant la voix de Dieu promulguer le Décalogue, il demanda comme une grâce que Moïse lui servit"],
    ["peut-être exprimée de plusieurs manières", "peut être exprimée de plusieurs manières"],
    ["(Ib. 5, 29.)", "(Ib. V, 29.)"],
    ["(Ib. 6, 13.)", "(Ib. VI, 13.)"],
    ["Mat. 5, 31", "Mat. V, 34"],
    ["(Ib. 8, 2.)", "(Ib. VIII, 2.)"],
    // ── p542 ──
    ["(Ib. 9, 6-8.)", "(Ib. IX, 6-8.)"],
    ["(Ib. 10, 1-4.)", "(Ib. X, 1-4.)"],
    ["en présente du Seigneur", "en présence du Seigneur"],
    ["''et il écrivit''sur les tables", "''et il écrivit'' sur les tables"],
    ["que c’est Dieu qui les a écrites\n", "que c’est Dieu qui les a écrites ?\n"],
    ["les discours et les évènements", "les discours et les événements"],
    // ── p543 ──
    ["l’amour de la, justice", "l’amour de la justice"],
    ["les dix « commandements", "les dix commandements"],
    ["mais. Il écrivit", "mais : Il écrivit"],
    ["rien antre chose", "rien autre chose"],
    ["dans ce paysage", "dans ce passage"],
    ["qui se trouve égaiement", "qui se trouve également"],
    ["entre les deux testaments", "entre les deux Testaments"],
    ["puisque, Dieu seul", "puisque Dieu seul"],
    ["et – leur – écriture", "et leur écriture"],
    ["écrit sur testables", "écrit sur les tables"],
    // ── p544 ──
    ["« ne connaissant pas « la justice", "« ne connaissant pas la justice"],
    ["qu’il la réalisât", "qu’il la réalisa"],
    ["eux – mêmes", "eux-mêmes"],
    ["les hommes s n’agissaient pas", "les hommes n’agissaient pas"],
    ["(Ib. 10, 8-9.)", "(Ib. X, 8, 9.)"],
    ["(Ib. 11, 20.)", "(Ib. XI, 20.)"],
    ["(Ib. 12, 11.)", "(Ib. XII, 11.)"],
    ["(Ib. 13, 1-3.)", "(Ib. XIII, 1, 2, 3.)"],
    ["de tout votre, cœur", "de tout votre cœur"],
    ["il ne faut par pour cela", "il ne faut pas pour cela"],
    // ── p545 ──
    ["(Ib. 14, 28-29.)", "(Ib. XIV, 28, 29.)"],
    ["si c’est trois ans, d’intervalle", "si c’est trois ans d’intervalle"],
    ["« Vous « séparerez une autre dîme", "« Vous séparerez une autre dîme"],
    ["Dieu, elfe devait profiter", "Dieu, elle devait profiter"],
    ["(Ib. 15, 9.)", "(Ib. XV, 9.)"],
    ["(Ib. 15, 12.)", "(Ib. XV, 12.)"],
    ["Hébreux d’origine, « t’ont été vendus", "Hébreux d’origine, t’ont été vendus"],
    ["et la « septième année", "et la septième année"],
    ["(Ib. 15, 19.)", "(Ib. XV, 19.)"],
    ["entre enfanté et engendre", "entre enfanté et engendré"],
    ["''prototoka''", "''πρωτότοκα''"],
    // ── p546 ──
    ["''tiktein''", "''τεκεῖν''"],
    ["''prototokon''", "''πρωτότοκον''"],
    ["''gennan''", "''γεννᾶν''"],
    ["''monotokos''", "''μονοτόκος''"],
    ["''monogenes''", "''μονογενής''"],
    ["Col. 5, 14", "Coloss. I, 18"],
    ["(Ib. 16, 2.)", "(Ib. XVI, 2.)"],
    ["Comment est-il ordonné d’immoler des bœufs à la Pâque.", "''Comment est-il ordonné d’immoler des bœufs à la Pâque''."],
    ["des beeufs", "des bœufs"],
    ["offerts pendants les jours", "offerts pendant les jours"],
    ["(Ib., 16, 9-11.)", "(Ib. XVI, 9, 10, 11.)"],
    ["(Ib. 17, 14-15.)", "(Ib. XVII, 14, 15.)"],
    // ── p547 ──
    ["« Tu « ne pourras point", "« Tu ne pourras point"],
    ["(Ib. 17, 17.)", "(Ib. XVII, 17.)"],
    ["(Ib. 18, 7-8.)", "(Ib. XVIII, 7, 8.)"],
    ["ses frères ; qui se tiennent en présence du Seigneur il mangera", "ses frères, qui se tiennent en présence du Seigneur ; il mangera"],
    ["(Ib. 18, 11.)", "(Ib. XVIII, 11.)"],
    ["demandent à être expliqué ; comme", "demandent à être expliqués ; comme"],
    ["avec la règle de la foi c’est ainsi", "avec la règle de la foi : c’est ainsi"],
    ["où se couvrait de rosée", "ou se couvrait de rosée"],
    ["(Ib. 20,4.)", "(Ib. XX, 4.)"],
    ["et te demander, non pas", "et le demander, non pas"],
    // ── p548 ──
    ["(Ib. 20, 5-7.)", "(Ib. XX, 5, 6, 7.)"],
    ["(Ib. 22, 5.)", "(Ib. XXII, 5.)"],
    ["des vêtements de guerre, désarmés", "des vêtements de guerre, des armes"],
    ["(Ib. 22, 18-24.)", "(Ib. XXII, 13-21.)"],
    ["en présente des anciens", "en présence des anciens"],
    ["elle à commis un crime", "elle a commis un crime"],
    ["condamné à, la lapidation", "condamné à la lapidation"],
    ["toujours uni, à la femme", "toujours uni à la femme"],
    ["(Ib. 22, 28-29.)", "(Ib. XXII, 28, 29.)"],
    // ── p549 ──
    ["précisément, 'qu’il refuse", "précisément, qu’il refuse"],
    ["(Ib. 23, 3-4.)", "(Ib. XXIII, 3, 4.)"],
    ["Ruth. 1, 23", "Ruth. I, 22"],
    ["dans ces paroles jusqu’à la dixième génération ? »", "dans ces paroles : « jusqu’à la dixième génération ? »"],
    ["Abrahain", "Abraham"],
    ["Animadab", "Aminadab"],
    ["et non, les femmes", "et non les femmes"],
    ["c’est que, après avoir vaincu", "c’est qu’après avoir vaincu"],
    ["qui attira, la ruine", "qui attira la ruine"],
    ["et.lesAmmonites", "et les Ammonites"],
    ["(Ib. 22, 15.)", "(Ib. XXIII, 15.)"],
    ["Défense de livrer à son maître l’esclave étranger qui se réfugiait en Israël.", "''Défense de livrer à son maître l’esclave étranger qui se réfugiait en Israël''. —"],
    ["''apposituma dominosuo''", "''appositum a domino suo''"],
    ["paraître, une injustice", "paraître une injustice"],
    ["à laquelle il parle, C’est", "à laquelle il parle. C’est"],
    ["(Ib. 23, 17.)", "(Ib. XXIII, 17.)"],
    ["Sur la défense de la fornication.—", "''Sur la défense de la fornication''. —"],
    // ── p550 ──
    ["Exod. Quest. 71, 4", "Exod. Quest. LXXI, 4"],
    ["(Ib. 23, 17-18.)", "(Ib. XXIII, 17, 18.)"],
    ["(Ib. 24, 7.)", "(Ib. XXIV, 7.)"],
    ["« Ce voleur »c’est-à-dire", "« Ce voleur » c’est-à-dire"],
    ["l’Église ?n’est-ce pas", "l’Église ? n’est-ce pas"],
    ["ce ; qui signifie", "ce qui signifie"],
    ["du vieil « homme »", "du vieil homme"],
    ["(Ib. 24, 8.)", "(Ib. XXIV, 8.)"],
    ["'''XLI.'''(Ib. 24, 10-13)", "'''XLI.''' (Ib. XXIV, 10-13.)"],
    // ── p551 ──
    ["condition imposée par la loi de rendre, le même jour", "condition imposée par la loi de rendre le même jour"],
    ["(Ib. 24, 16.)", "(Ib. XXIV, 16.)"],
    ["mats encore dans la Loi", "mais encore dans la Loi"],
    ["</ref>? »", "</ref> ? »"],
    ["tandis que ces paroles ;", "tandis que ces paroles :"],
    ["trois et quatre fois'', je ne changerai pas mon, arrêt", "trois et quatre fois'', je ne changerai pas mon arrêt"],
    ["(Ib. 24, 17.)", "(Ib. XXIV, 17.)"],
    ["Vous ne prendrez point engage", "Vous ne prendrez point en gage"],
    // ── p552 ──
    ["de toute espèce de secours car si", "de toute espèce de secours : car si"],
    ["autrement que dans ta désolation", "autrement que dans la désolation"],
    ["(Ib. 24, 19.)", "(Ib. XXIV, 19.)"],
    ["(Ib. 25, 1-3.)", "(Ib. XXV, 1-3.)"],
    ["devant le tribunal ils le jugeront", "devant le tribunal, ils le jugeront"],
    ["pour des fautes quine méritent", "pour des fautes qui ne méritent"],
    ["ou un autre peine plus douce", "ou une autre peine plus douce"],
    ["'''XLVI.''' ([b. 25, 5.)", "'''XLVI.''' (Ib. XXV, 5.)"],
    // ── p553 ──
    ["saint Joseph ne redut le nom", "saint Joseph ne reçut le nom"],
    ["« Il sera admis « au nom du défunt »", "« Il sera admis au nom du défunt »"],
    ["« Et son nom ne sera pas effacé « d’Israël »", "« Et son nom ne sera pas effacé d’Israël »"],
    ["Israël, quoique l’enfant n’ait point porté son nom.\n'''2.'''", "Israël, quoique l’enfant n’ait point porté son nom.\n<br>'''2.'''"],
    ["les noms diffèrent de nouveau ainsi suivant saint Luc", "les noms diffèrent de nouveau : ainsi suivant saint Luc"],
    // ── p554 ──
    ["du défunt, où l’adoption donna", "du défunt, ou l’adoption donna"],
    ["(Ib. 26, 13-14.)", "(Ib. XXVI, 13, 14.)"],
    ["bien rempli fous ses devoirs", "bien rempli tous ses devoirs"],
    ["''à un mort''? »", "''à un mort'' ? »"],
    ["(Ib. 28, 14.)", "(Ib. XXVIII, 14.)"],
    ["et que adorer les dieux", "et qu’adorer les dieux"],
    ["mais, sur celui-là même", "mais sur celui-là même"],
    ["avoir le, sens complet", "avoir le sens complet"],
    ["Tu ne l’éloigneras pas de toutes", "Tu ne t’éloigneras pas de toutes"],
    // ── p555 ──
    ["(Ib. 29, 1.)", "(Ib. XXIX, 1.)"],
    ["(Ib. 29,2-4.)", "(Ib. XXIX, 2, 3, 4.)"],
    ["a fait.devantvous", "a fait devant vous"],
    ["des yeux pourvoir", "des yeux pour voir"],
    ["« Et « le Seigneur Dieu", "« Et le Seigneur Dieu"],
    ["(Ib. 29, 5-6.)", "(Ib. XXIX, 5, 6.)"],
    // ── p556 ──
    ["Moïse d’ailleurs, le prouve", "Moïse d’ailleurs le prouve"],
    ["(Ib. 29, 18-21.)", "(Ib. XXIX, 18-21.)"],
    ["médite des pareilles pensées", "médite de pareilles pensées"],
    ["avec lui celui qui « est sans péché", "avec lui celui qui est sans péché"],
    ["Heureux ceux qui ont le cœur pur, parce qu’ils verront Dieu<ref>[[Bible_Crampon_1923/Genèse#20|Gen. 20, 6]]", "Heureux ceux qui ont le cœur pur, parce qu’ils verront Dieu<ref>Matth. V, 8."],
    ["(Ib. 30, 6.)", "(Ib. XXX, 6.)"],
    ["(Ib. 30, 11-12 etc.)", "(Ib. XXX, 11, 12, etc.)"],
    ["ni éloigné de vous il n’est point", "ni éloigné de vous ; il n’est point"],
    ["en d’autres termes.desorte", "en d’autres termes, de sorte"],
    ["au de-là de lamer", "au delà de la mer"],
    // ── p557 ──
    ["Maison peut demander", "Mais on peut demander"],
    ["un chapitre précédent<ref>[[Bible_Crampon_1923/Romains#10|Rom. 10, 7]]</ref>", "un chapitre précédent<ref>Deut. XXIX, 21.</ref>"],
    ["au-delà de lamer", "au-delà de la mer"],
    ["Luc. 11", "Luc. II"],
    ["(Ib. 32, 5.)", "(Ib. XXXII, 5.)"],
    ["''teknamometa''", "''τέκνα μωμητά''"],
    ["ou plutôt il, n’y a", "ou plutôt il n’y a"],
    ["du livre, des Psaumes", "du livre des Psaumes"],
    // ── p558 ──
    ["Jn. 14, 30-41", "Jean, XIV, 30, 31"],
    ["par sof1 prophète", "par son prophète"],
    ["qu’ils se sont pas à eux-mêmes", "qu’ils se sont nuis à eux-mêmes"],
    ["(Ib. 33, 3-4.)", "(Ib. XXXIII, 1-3.)"],
    ["puisque. Séïr est une montagne.dupays", "puisque Séïr est une montagne du pays"],
    ["quand Moise a béni", "quand Moïse a béni"],
    ["sanctifié parla grâce", "sanctifié par la grâce"],
    // ── p559 ──
    ["parle ici l’Ecriture", "parle ici l’Écriture"],
    ["Si vous croyiez Moise", "Si vous croyiez Moïse"],
    ["Moise dit de cette Loi", "Moïse dit de cette Loi"],
    ["(Ib. 33, 17.)", "(Ib. XXXIII, 17.)"],
    ["''primo genitus tauri, pulchrit udoejus''", "''Primogenitus tauri, pulchritudo ejus''"],
    ["''primo genitus tauri''", "''primogenitus tauri''"],
  ],
  LABEL_SIC: [],
}
