// Livre VII — Questions sur les Juges. Pages 573-597 (fin de l'oeuvre).
// Particularite : l'OCR a fondu la mention du traducteur dans le titre de la
// premiere question, en italique au lieu du gras. Retabli ci-dessous ; a
// verifier au fac-simile (l'agent de controle tranchera la forme exacte).
export default {
  NORM: [[/c’est-à- dire/g, "c’est-à-dire"]],
  cle: "juges", fichier: "Juges_draft",
  titre: "Livre septième — Questions sur les Juges",
  titreCourt: "Juges",
  de: 573, a: 597, debutSection: null, finSection: null,
  CORR: [
    ["c’est-à- dire", "c’est-à-dire"],
    // Q XLIX : après 25, l'édition saute 26 et imprime directement 27.
    ["'''27.''' « Et Jephté fit un vœu", "'''27.''' ⟦sic⟧ « Et Jephté fit un vœu"],
    ["''Cette traduction est l’œuvre de M. l’abbé POGNON PREMIÈRE QUESTION. (Juges. I.)''",
     "'''PREMIÈRE QUESTION.''' (Juges. I.)"],

    // ── p573 ──
    ["les évènements qui précédèrent", "les événements qui précédèrent"],
    ["(Ib. 1, 1-3)", "(Ib. I, 1-3.)"],
    ["le Seigneur, disant qui marchera", "le Seigneur, disant : qui marchera"],
    ["la nation en masse prit les armes", "la nation en masse prît les armes"],
    ["(Ib. 1, 9-12.)", "(Ib. I, 9-12.)"],
    ["placé parle récit", "placé par le récit"],

    // ── p574 ──
    ["l’Écriture a en quelque raison", "l’Écriture a eu quelque raison"],
    ["(Ib. 1,14-15.)", "(Ib. I, 14, 15.)"],
    ["Récits concordants dit livre", "Récits concordants du livre"],
    ["C’est comme si.l'ondisait", "C’est comme si l’on disait"],
    ["dans les planés où les vallées", "dans les plaines ou les vallées"],
    ["(Ib. 1, 18-19.)", "(Ib. I, 18, 19.)"],
    ["ni Azothet les pays environnants", "ni Azoth et les pays environnants"],
    ["une réflexion prudente Dieu dans sa miséricorde", "une réflexion prudente : Dieu dans sa miséricorde"],
    ["(Ib 1, 20.)", "(Ib. I, 20.)"],

    // ── p592 ──
    ["Gen. 24-48", "Gen. XXXII, 24-28."],
    ["dans la maison de notre « père", "dans la maison de notre père"],
    ["Jn. 9, 16", "Jean, IX, 16."],
    ["Id. 8, 41", "Ib. VIII, 41."],
    ["1Co. 2, 8", "I Cor. II, 8."],
    ["Mat. 9, 11-12", "Matth. IX, 11, 12."],
    ["Isa. 53, 12", "Isaïe, LIII, 12."],
    ["Luc. 22, 33, 43", "Luc. XXIII, 33, 43."],
    ["Psa. 50, 16", "Ps. L, 15."],
    ["pour qu’il te délivrât de leurs ennemis", "pour qu’il les délivrât de leurs ennemis"],
    ["componction dans leur tueur", "componction dans leur cœur"],
    ["Act. 2, 22-38", "Act. II, 22-38."],
    ["telle plutôt encore la multitude d’Israël, ont la vocation", "telle plutôt encore la multitude d’Israël, dont la vocation"],
    ["C’est plutôt ; en effet", "C’est plutôt, en effet"],
    ["derniers temps.''Galaad''", "derniers temps. ''Galaad''"],
    ["persévéreront dam l’infidélité", "persévéreront dans l’infidélité"],
    ["ou bien de tors ceux", "ou bien de tous ceux"],
    ["Mat. 25, 30", "Matth. XXV, 30."],

    // ── p593 ──
    ["Comment, venez-vous à moi", "Comment venez-vous à moi"],
    ["Id. 47-48", "Ib. XLII-XLIV."],
    ["C’est a ce peuple ennemi", "C’est à ce peuple ennemi"],
    ["qui doivent venin au Christ", "qui doivent venir au Christ"],
    ["Luc. 1, 83", "Luc. I, 33."],
    ["1Sa. 10, I", "I Rois, X, 1."],
    ["et il à des successeurs", "et il eut des successeurs"],
    ["Deu. 17, 14", "Deut. XVII, 14."],
    ["Jn. 19, 19-22", "Jean, XIX, 19-22."],
    ["il, faut croire", "il faut croire"],
    ["raison que, Jephté répondit", "raison que Jephté répondit"],
    ["1Co. 11, 3", "I Cor. XI, 3."],
    ["Eph. 5, 21", "Éphés. V, 21."],
    ["Jug. 12, 7", "Jug. XII, 7."],
    ["Rom. 12, 18", "Rom. XII, 18."],
    ["2Ti. 2, 19", "II Tim. II, 19."],
    ["au-delà des enfants d’Aramon", "au-delà des enfants d’Ammon"],
    ["Les ''hauteur'' s sont", "Les ''hauteurs'' sont"],

    // ── p594 ──
    ["au retour du triomphe « remporté", "au retour du triomphe remporté"],
    ["celui-là sera « au Seigneur", "celui-là sera au Seigneur"],
    ["qu’une telle pensée s’accomplit", "qu’une telle pensée s’accomplît"],
    ["en faisant son veau", "en faisant son vœu"],
    ["Eph. 5, 31-32.", "Éphés. V, 31, 32."],
    ["Mat. 9, 20-22", "Matth. IX, 20-22."],
    ["Id. 15", "Ib. 15."],
    ["les jours ou l’époux", "les jours où l’époux"],
    ["2Co. 10, 1-2", "II Cor. X, 1, 2."],
    ["1Co. 15, 54, 24", "I Cor. XV, 54, 24."],
    ["c’est le deuxième âgé", "c’est le deuxième âge"],
    ["jusqu’à la fin du siècle Ces six âges", "jusqu’à la fin du siècle. Ces six âges"],
    ["Mat. 6, 12", "Matth. VI, 12."],
    ["qui aura lieu élans la vie éternelle", "qui aura lieu dans la vie éternelle"],
    ["des temps écoulés du pèlerinage, de l’Église", "des temps écoulés du pèlerinage de l’Église"],

    // ── p595 ──
    ["les Israélites sont, je pense, institué cet usage", "les Israélites ont, je pense, institué cet usage"],
    ["'''20.''' Le peuple d’Ephrem", "'''29.''' Le peuple d’Ephrem"],
    ["Luc. 19, 27", "Luc. XIX, 27."],
    ["Jug. 12, 4-6", "Jug. XII, 4, 6."],
    ["De meule que les deux mois", "De même que les deux mois"],
    ["(Ib. 13, 4) ''Recommandation", "(Ib. XIII, 4.) ''Recommandation"],
    ["Deu. 14, 3-19", "Deut. XIV, 3-19."],
    ["(Ib. 13, 6.)", "(Ib. XIII, 6.)"],
    ["il ne me la point fait connaître", "il ne me l’a point fait connaître"],
    ["(Ib. 13, 7, 5.)", "(Ib. XIII, 7, 5.)"],
    ["ce quine lui aurait point été dit", "ce qui ne lui aurait point été dit"],
    ["Nom. 6, 2-21.", "Nomb. VI, 2-21."],
    ["(Ib. 13, 16, 15, 1.).''Sur l’entretien", "(Ib. XIII, 16, 15, 1.) ''Sur l’entretien"],

    // ── p596 ──
    ["que nous offrions en la présence un chevreau", "que nous offrions en ta présence un chevreau"],
    ["il avait été invite à un repas", "il avait été invité à un repas"],
    ["Il ajouté ensuite", "Il ajoute ensuite"],
    ["Exo. 33, 20.", "Ex. XXXIII, 20."],
    ["Ilscroyaient.doncavoir vu Dieu", "Ils croyaient donc avoir vu Dieu"],
    ["dans là personne d’un Ange", "dans la personne d’un Ange"],
    ["où bien regardaient-ils l’ange", "ou bien regardaient-ils l’ange"],
    ["vivre ; biais Dieu parlant", "vivre ; mais Dieu parlant"],
    ["« ma face. »Manué", "« ma face. » Manué"],
    ["Si le, Seigneur avait voulu", "Si le Seigneur avait voulu"],
    ["Isa. 9, 6.", "Is. IX, 6."],
    ["(Ib. 15, 8, 45.)", "(Ib. XV, 8, 15.)"],
    ["Oui à la jambe sur la cuisse", "Qui a la jambe sur la cuisse"],

    // ── p597 ──
    ["d’une manière tout à fait étonnante'';", "d’une manière tout à fait étonnante'' ;"],
    ["qu’il les frappa «''la jambe sur la cuisse''. »", "qu’il les frappa « ''la jambe sur la cuisse''. »"],
    ["aux hommes de Juda « Faites-moi serment", "aux hommes de Juda : « Faites-moi serment"],
    ["vous ne veniez à ma rencontre''? »", "vous ne veniez à ma rencontre'' ? »"],
    ["''allège-le'', ce qui signifie mets-le à mort", "''allège-le'', ce qui signifie ''mets-le à mort''"],
    ["1Ro. 2, 29.", "II Rois, II, 29."],

    // ── p575 ──
    ["ce qui concerné la tribu", "ce qui concerne la tribu"],
    ["(Ib. 1,21, 8.)", "(Ib. I, 21, 8.)"],
    ["dans le partagé même du pays", "dans le partage même du pays"],
    ["les autres, â l’exception", "les autres, à l’exception"],
    ["soit qu’il, y en ait eu", "soit qu’il y en ait eu"],
    ["commune avec Juda C’est pourquoi", "commune avec Juda. C’est pourquoi"],
    ["signifie, en tout, cas", "signifie, en tout cas"],
    ["(Ib. 1, 27.) ''Comment les Scythes", "(Ib. I, 27.) ''Comment les Scythes"],
    ["si éloignées de la Scythes", "si éloignées de la Scythie"],
    ["(Ib. 1, 27.) ''Les villes", "(Ib. I, 27.) ''Les villes"],
    ["(Ib. 1, 28.)", "(Ib. I, 28.)"],
    ["«. Et quand Israël", "« Et quand Israël"],
    ["ou bien alors ou racontait", "ou bien alors on racontait"],
    ["(Ib. 1, 34.)", "(Ib. I, 34.)"],
    ["(Ib. 2, 1.)", "(Ib. II, 1.)"],
    ["''klauthmos''", "''κλαυθμός''"],

    // ── p576 ──
    ["tout le peuple parle ministère", "tout le peuple par le ministère"],
    ["rien de pareil n’eut lieu", "rien de pareil n’eût lieu"],
    ["(Ib. 2, 3.)", "(Ib. II, 3.)"],
    ["de détruire, périsse. « Je ne les ôterai", "de détruire, périsse. Je ne les ôterai"],
    ["pécher contre le leur Dieu", "pécher contre leur Dieu"],
    ["(Ib. 2, 6, 8.)", "(Ib. II, 6, 8.)"],
    ["(Ib, 2, 10.)", "(Ib. II, 10.)"],
    ["(Ib. 2, 13.)", "(Ib. II, 13.)"],
    ["la langue panique", "la langue punique"],
    ["Ce n’est pas une difficulté lue le nom", "Ce n’est pas une difficulté que le nom"],
    ["celui de Junon an pluriel", "celui de Junon au pluriel"],
    ["la multitude ides idoles", "la multitude des idoles"],

    // ── p577 ──
    ["(Ib. 2, 10, 23 ; 3, 1, 4.)", "(Ib. II, 10, 23 ; III, 1, 4.)"],
    ["et pourquoi ne sont-ils pas plutôt ''donnés''?", "et pourquoi ne sont-ils pas plutôt ''donnés'' ?"],
    ["des nations que Jésus fils de Navéa laissées, qu’il a laissées pour éprouver Israël", "des nations que Jésus fils de Navé a laissées, qu’il a laissées pour éprouver Israël"],
    ["que cette épreuve n’aboutit pas", "que cette épreuve n’aboutît pas"],
    ["la piété dans le guerre", "la piété dans la guerre"],

    // ── p578 ──
    ["leur conscience leur rendit un bon", "leur conscience leur rendît un bon"],
    ["</ref>. Dieu pouvait exécuter", "</ref>. » Dieu pouvait exécuter"],
    ["(Ib. 3, 9.)", "(Ib. III, 9.)"],
    ["« Les « enfants d’Israël crièrent", "« Les enfants d’Israël crièrent"],
    ["et il les sauva, « Gothoniel", "et il les sauva, Gothoniel"],
    ["(Ib. 3, 11.)", "(Ib. III, 11.)"],
    ["(Ib. 3, 19, 20.)", "(Ib. III, 19, 20.)"],
    ["Aoddit de nouveau", "Aod dit de nouveau"],

    // ── p579 ──
    ["c’était le cas donc cette circonstance", "c’était le cas dans cette circonstance"],
    ["(Ib. 3, 17.)", "(Ib. III, 17.)"],
    ["extrêmement grêlé", "extrêmement grêle"],
    ["le ''défaut'' parle terme", "le ''défaut'' par le terme"],
    ["d’un excessif embonpoint.\n", "d’un excessif embonpoint. »\n"],
    ["(Ib. 3, 23.)", "(Ib. III, 23.)"],
    ["serviteurs du roi Eglonont pu", "serviteurs du roi Eglon ont pu"],
    ["(Ib. 3, 25.)", "(Ib. III, 25.)"],
    ["Sous.lajudicature d’Aod", "Sous la judicature d’Aod"],
    ["(Ib. 3, 30.)", "(Ib. III, 30.)"],
    ["parutSamgarfils d’Aneath", "parut Samgar fils d’Aneath"],
    ["Samgara combattu pour Israël", "Samgar a combattu pour Israël"],
    ["de veaux à, des bœufs", "de veaux à des bœufs"],
    ["(Ib. 4, 8.)", "(Ib. IV, 8.)"],
    ["Le Seigneur favorisé son ange", "Le Seigneur favorise son ange"],
    ["(Ib. 4, 15.)", "(Ib. IV, 15.)"],
    ["donnant aux évènements l’issue", "donnant aux événements l’issue"],
    ["(Ib. 4, 22.)", "(Ib. IV, 22.)"],

    // ── p580 ──
    ["dans leur sen naturel", "dans leur sens naturel"],
    ["(Ib. 5, 7, 8.)", "(Ib. V, 7, 8.)"],
    ["et que alors, ils", "et qu’alors ils"],
    ["une question. Comment", "une question : Comment"],
    ["Israël. ; alors ils", "Israël ; alors ils"],
    ["d’exprimer cette pensée de même", "d’exprimer cette pensée : de même"],
    ["comme si t’eût été", "comme si c’eût été"],
    ["(Ib. 5, 8.)", "(Ib. V, 8.)"],
    ["(Ib. 6, 8, 11.)", "(Ib. VI, 8, 11.)"],
    ["les Israélites« crièrent", "les Israélites « crièrent"],
    ["un ange quia été désigné", "un ange qui a été désigné"],
    ["(Ib. 6, 12.)", "(Ib. VI, 12.)"],
    ["(Ib. 6, 14.)", "(Ib. VI, 14.)"],
    ["la place de Dieu « N’est-ce point", "la place de Dieu : « N’est-ce point"],
    ["sinon Celui quia député", "sinon Celui qui a député"],

    // ── p581 ──
    ["(Ib. 6, 15.)", "(Ib. VI, 15.)"],
    ["''À moi, Seigneur''!", "''À moi, Seigneur'' !"],
    ["''chiliarques''?", "''chiliarques'' ?"],
    ["(Ib. 6, 18-20.)", "(Ib. VI, 18-20.)"],
    ["ce qui l’ait comprendre", "ce qui fait comprendre"],
    ["mais il dit à celui-ci. « Prends les chairs", "mais il dit à celui-ci : « Prends les chairs"],
    ["(Ib. 6, 20.)", "(Ib. VI, 20.)"],
    ["Dieu avait détendu qu’on lui offrît", "Dieu avait défendu qu’on lui offrît"],
    ["par révélation, et inspiration", "par révélation et inspiration"],
    ["que le sacrifice l’ut offert", "que le sacrifice fut offert"],
    ["répandu sur nous très abondamment", "répandu sur nous très-abondamment"],
    ["sortiront « de ses entrailles", "sortiront de ses entrailles"],

    // ── p582 ──
    ["sur chacun deux", "sur chacun d’eux"],
    ["le Seigneur lui-même dit « Je suis venu", "le Seigneur lui-même dit : « Je suis venu"],
    ["(Ib. 7, 6.)", "(Ib. VII, 6.)"],
    ["Ce nombre figure la, croix", "Ce nombre figure la croix"],
    ["dans sou infirmité", "dans son infirmité"],
    ["(Ib. 7, 11.)", "(Ib. VII, 11.)"],
    ["Gédéon descendit lui-même « avec son serviteur", "Gédéon descendit lui-même avec son serviteur"],
    ["vers le côté « du camp", "vers le côté du camp"],
    ["(Ib. 7, 13.)", "(Ib. VII, 13.)"],

    // ── p583 ──
    ["(Ib. 7, 20.)", "(Ib. VII, 20.)"],
    ["(Ib. 8, 26, 27.)", "(Ib. VIII, 26, 27.)"],
    ["l’éphod, ou l’éphod", "l’éphod, ou l’éphud"],
    ["''επεδυμα''", "''ἐπένδυμα''"],
    ["''επομις''", "''ἐπωμίς''"],
    ["un éphod le lin", "un éphod de lin"],
    ["Ici une, question naturelle", "Ici une question naturelle"],
    ["la dignité sacerdotale Le péché", "la dignité sacerdotale. Le péché"],

    // ── p584 ──
    ["(Ib. 8, 27, 28.)", "(Ib. VIII, 27, 28.)"],
    ["la terre tutelle en repos", "la terre fut-elle en repos"],
    ["vers latin des jours", "vers la fin des jours"],
    ["(Ib. 8, 33.)", "(Ib. VIII, 33.)"],
    ["Baalim et, Baalbérith", "Baalim et Baalbérith"],
    ["(Ib. 9, 14, 15.)", "(Ib. IX, 14, 15.)"],
    ["Le sens de ce passage st obscur", "Le sens de ce passage est obscur"],

    // ── p585 ──
    ["tombe a l’instant", "tombe à l’instant"],
    ["la menace à quelque chose", "la menace a quelque chose"],
    ["(Ib. 9, 23.)", "(Ib. IX, 23.)"],
    ["comme dans le Psaume « Envoyez", "comme dans le Psaume : « Envoyez"],
    ["(Ib. 9, 32, 33.)", "(Ib. IX, 32, 33.)"],
    ["''manicabis'';", "''manicabis'' ;"],
    ["''ὀρθρος''", "''ὄρθρος''"],
    ["(Ib. 10, 1.)", "(Ib. X, 1.)"],
    ["« Après Abimélech, ce fut Thola « qui s’éleva", "« Après Abimélech, ce fut Thola qui s’éleva"],
    ["Le pré-prêtre", "Le prêtre"],

    // ── p586 ──
    ["(Ib. 11, 24.)", "(Ib. XI, 24.)"],
    ["tout ce que, Chamos ton dieu", "tout ce que Chamos ton dieu"],
    ["tout ce que, ''pour toi'', Chamos", "tout ce que ''pour toi'', Chamos"],
    ["quand il y aune autre", "quand il y a une autre"],
    ["tu as cette croyance cela ne veut", "tu as cette croyance ; cela ne veut"],
    ["car il a ; enlevé", "car il a enlevé"],

    // ── p587 ──
    ["comtat jusqu’à la mort", "combat jusqu’à la mort"],
    ["le sang que Jésus à lui-même versé", "le sang que Jésus a lui-même versé"],
    ["immolés parla cruauté", "immolés par la cruauté"],
    ["l’Écriture dit « Il les a éprouvés", "l’Écriture dit : « Il les a éprouvés"],
    ["comment, dira-t-on ; Abraham", "comment, dira-t-on : Abraham"],
    ["son maître à prescrit", "son maître a prescrit"],
    ["Quant àJéphté il a", "Quant à Jephté, il a"],
    ["et dit : « Si vous livrez", "et dit : « Si vous livrez"],

    // ── p588 ──
    ["l’Écriture à l’usage", "l’Écriture a l’usage"],
    ["sans blâme n approbation", "sans blâme ni approbation"],
    ["cette femme pour une prostituée elle laisse", "cette femme pour une prostituée ; elle laisse"],
    ["Samson,.et Jephté", "Samson, et Jephté"],
    ["Voilà le premier témoignage voici le second", "Voilà le premier témoignage ; voici le second"],
    ["'''6.''' Premièrement", "'''6.''' ⟦sic⟧ Premièrement"],

    // ── p589 ──
    ["Jug. 6, 31", "Jug. VI, 31."],
    ["d’avoir fabriqué, avec l’or du butin", "d’avoir fabriqué avec l’or du butin"],
    ["Id. 8, 27", "Ib. VIII, 27."],
    ["« qui, par la foi ont dompté", "« qui par la foi ont dompté"],
    ["à la foi et a la justice", "à la foi et à la justice"],
    ["Ib, 6, 39", "Ib. VI, 39."],
    ["ne pécha, point, contre", "ne pécha point contre"],
    ["Deu. 6, 16", "Deut. VI, 16."],
    ["à l’avance, ainsi, la toison", "à l’avance ; ainsi, la toison"],
    ["L’Esprit du Seigneur, fut sur Jephté", "L’Esprit du Seigneur fut sur Jephté"],
    ["tout ce qui arriva, ensuite", "tout ce qui arriva ensuite"],
    ["succès obtenu par ses arrhes", "succès obtenu par ses armes"],
    ["carnage de.l'ennemi", "carnage de l’ennemi"],
    ["servir a ses desseins", "servir à ses desseins"],
    ["lorsqu’il.persécutaitDavid", "lorsqu’il persécutait David"],
    ["1Sa. 19, 20-24", "I Rois, XIX, 20-24."],
    ["inspira, à ce juge d’Israël", "inspira à ce juge d’Israël"],
    ["Jn. 11, 49-51", "Jean, XI, 49-51."],

    // ── p590 ──
    ["Gédeon, en tout ceci", "Gédéon, en tout ceci"],
    ["par la même, comme le stratagème", "par là même, comme le stratagème"],
    ["Gen. 27, 15,16", "Gen. XXVII, 15, 16."],
    ["Jug. 7, 16-22", "Jug. VII, 16-22."],
    ["Gédéon parait avoir agi", "Gédéon paraît avoir agi"],
    ["selon cette parole de l’Apôtre« Nous portons", "selon cette parole de l’Apôtre : « Nous portons"],
    ["2Co. 4, 7", "II Cor. IV, 7."],
    ["fussent-ils figuré de ce qu’il convient de croire", "fussent-ils figure de ce qu’il convient de croire"],
    ["suivant la, justice", "suivant la justice"],
    ["victimes d’animaux étant d’un lisage quotidien", "victimes d’animaux étant d’un usage quotidien"],

    // ── p591 ──
    ["Cité de Dieu, l. 1, ch. 21.", "Cité de Dieu, l. I, ch. 21."],
    ["Luc. 24, 45, 27", "Luc. XXIV, 45, 27."],
    ["Jug. 8, 27 ; 10, 6-8", "Jug. VIII, 27 ; X, 6, 8."],
  ],
  LABEL_SIC: [],
}
