// Livre III — Questions sur le Lévitique. Pages 478-512 (section s1 sur la 512).
// Corrections vérifiées au fac-similé (contrôle image intégral).
// ⟦sic⟧ = coquille réellement imprimée par l'édition, conservée.
export default {
  cle: "levitique", fichier: "Levitique_draft",
  titre: "Livre troisième — Questions sur le Lévitique",
  titreCourt: "Lévitique",
  de: 478, a: 512, debutSection: null, finSection: "s1",

  // Notes ajoutées par Wikisource, absentes du fac-similé : écartées au titre de
  // la règle « texte de l'édition seul » (2 occurrences, p483).
  NORM: [
    [/<ref>\s*Correspond au verset[^<]*<\/ref>/g, ""],
    [/Faut- il/g, "Faut-il"],
    [/l’ âme/g, "l’âme"],
    [/c’est- à-dire/g, "c’est-à-dire"],
  ],

  CORR: [
    ["Faut- il", "Faut-il"],
    ["l’ âme", "l’âme"],
    ["c’est- à-dire", "c’est-à-dire"],
    // ── p478-483 ──
    ["s’en soit ouvert à lui car il a pu ainsi", "s’en soit ouvert à lui : car il a pu ainsi"],
    ["Car nos-conseils ou notre défense", "Car nos conseils ou notre défense"],
    ["de tout péché, sil révèle ce qu’il sait", "de tout péché, s’il révèle ce qu’il sait"],
    ["« Quiconque, par, une parole précise", "« Quiconque, par une parole précise"],
    ["aura été précisé dans le sûrement", "aura été précisé dans le serment"],
    ["Ne faut-il pas admettre que ce sacrifice", "Ne faut il ⟦sic⟧ pas admettre que ce sacrifice"],
    ["divers péchés ; se trouvent quelques obscurités", "divers péchés, se trouvent quelques obscurités"],
    ["d’après la distinction de la Loi, classés parmi", "d’après la distinction de la Loi classés parmi"],
    ["Psa. 65, 13-14", "Psa. 65, 13, 14"],
    ["on distingue une chose ries autres qui ne peuvent être ; exprimées par un seul mot", "on distingue une chose des autres qui ne peuvent être exprimées par un seul mot"],
    ["comme si une jeune brebis et une jeune chèvre pouvaient être prises", "comme si une jeune berbis ⟦sic⟧ et une jeune chèvre pouvaient être prises"],
    ["cette formule. : « Si après cela il connaît, et commet le délit ; »", "cette formule : « Si après cela il connait, et commet le délit ; »"],
    ["que pour un délit que l’on connaît ?", "que pour un délit que l’on connait ?"],
    ["Si après cela il connaît sa faute et s’en repent", "Si après cela il connait sa faute et s’en repent"],
    ["« Si après cela il connaît, et commet le délit », sinon que", "« Si après cela il connait, et commet le délit », sinon que"],
    ["Dieu ne semble y avoir, en vue que les péchés", "Dieu ne semble y avoir en vue que les péchés"],
    ["avant « ''il a commis le délit'': »", "avant « ''il a commis le délit''. »"],
    ["et le reconnaît par la suite", "et le reconnait par la suite"],
    ["l’un pour le péché, et l’autre en holocauste. » Ce texte éclaircit", "l’un pour le péché, et l’autre en holaucauste ⟦sic⟧. » Ce texte éclaircit"],
    ["''anima silatueriteum''", "''anima si latuerit eum''"],
    ["(Ib. 5, 15,16.)", "(Ib. 5, 15, 16.)"],
    ["chose semblable réservée aux prêtres", "chose semblable reservée ⟦sic⟧ aux prêtres"],
    ["la dixième partie d’un éphide fleur de farine", "la dixième partie d’un éphi de fleur de farine"],
    ["Lev 4.]]", "Lev. 4.]]"],
    ["Id. 4, 1.3, 22, etc.]]", "Id. 4, 13, 22 etc.]]"],
    ["à quoi bon dès lors prescrire", "à quoi bon dés ⟦sic⟧ lors prescrire"],
    ["nous exprimerions la même pensée de la manière suivante Tout péché", "nous exprimerions la même pensé ⟦sic⟧ de la manière suivante : Tout péché"],
    ["mais celui qui.commetla fornication", "mais celui qui commet la fornication"],
    ["on aurait pu traire que son but", "on aurait pu croire que son but"],
    ["celui qui l’offrirait saris l’avoir acheté", "celui qui l’offrirait sans l’avoir acheté"],
    ["ce qui signifie que le bélier coûtera plusieurs sicles", "ce qui signifie que le belier ⟦sic⟧ coûtera plusieurs sicles"],
    ["l’holocauste que le feu aura, consumé", "l’holocauste que le feu aura consumé"],
    // Le scan n'imprime pas « κάρπωμα » après « holocarpoma » : ajout étranger.
    ["''holocarpoma κάρπωμα'' et ''holocaustosis''", "''holocarpoma'' et ''holocaustosis''"],
    ["Le mot convenable rie serait-il par celui", "Le mot convenable ne serait-il par ⟦sic⟧ celui"],
    ["le texte se rétablirait comme il suit « Cet holocauste", "le texte se rétablirait comme il suit : « Cet holocauste"],
    ["c’est ce qui a été consumé parle feu", "c’est ce qui a été consumé par le feu"],
    ["nous lisons ''katakarposis''", "nous lisons ''κατάκαρπωσις''"],
    ["et ils ont traduit « Il jettera hors du camp", "et ils ont traduit : « Il jettera hors du camp"],
    ["un seul jour, saris que l’holocauste", "un seul jour, sans que l’holocauste"],
    ["les victimes qu’il avait commandés d’offrir", "les victimes qu’il avait commandé d’offrir"],
    ["aurait commencé par parler de celui-là il serait extraordinaire", "aurait commencé par parler de celui-là : il serait extraordinaire"],
    ["au Seigneur, quel que soit le jour où tu lui donneras l’onction. »", "au Seigneur, quelque ⟦sic⟧ soit le jour où tu lui donneras l’onction. »"],
    ["au jour de sa consécration, c’est-à-dire, de son onction", "au jour de sa consécracration ⟦sic⟧, c’est-à-dire, de son onction"],
    ["La dixième partie d’un éphide fleur de farine", "La dixième partie d’un éphi de fleur de farine"],
    ["l’expression grecque ''epikta''", "l’expression grecque ''ἐρικτά''"],
    ["s’applique-t-il à la poudre très fine de la fleur de farine", "s’applique-t-il à la poudre trés ⟦sic⟧-fine de la fleur de farine"],
    // La question XVI existe bien dans l'édition ET dans l'OCR, mais son balisage
    // gras avait sauté : elle était invisible au découpage.
    ["XVI. (Ib. 6, 21, 23.) ''Continuation''", "\n'''XVI.''' (Ib. 6, 21, 23.) ''Continuation''"],
    ["Le mot perpétuel » signifiait donc", "Le mot « perpétuel » signifiait donc"],
    ["prendre ces mots « Tout sera consumé. »", "prendre ces mots : « Tout sera consumé. »"],
    ["l’autel de l’encens placé.dansle tabernacle", "l’autel de l’encens placé dans le tabernacle"],

    // ── p484-489 ──
    ["Lev. 4, 12 ; 24", "Lev. 4, 12, 24"],
    ["cette vie finie est très-sainte", "cette victime est très-sainte"],
    ["ajoute-t-elle « Comme on fait pour le ''péché''", "ajoute-t-elle : « Comme on fait pour le ''péché''"],
    ["''paraptroma'' et", "''παράπτωμα'' et"],
    ["par ''ptoma'', qui vient de ''piptein (apo tou piptein)''", "par ''πτῶμα'', qui vient de ''πίπτειν (ἀπό τοῦ πίπτειν)''"],
    ["se rend en grec par ''ameleia'', par la raison", "se rend en grec par ''ἀμέλεια'', par la raison"],
    ["par ''ou melei moi''", "par ''οὐ μέλει μοι''"],
    ["la particule ''plem''", "la particule ''πλήμ''"],
    ["hors de ; ''ameleia'', qui veut dire négligence", "hors de ; ''ἀμέλεια'', qui veut dire négligence"],
    ["préféré ''''negligentiam'' à ''delictum''", "préféré ''negligentiam'' à ''delictum''"],
    ["en grec par ''ἁμαρτίας'' ?", "en grec par ''ἁμαρτία'' ?"],
    ["Mais d’ou vient ''peccatum''", "Mais d’ou ⟦sic⟧ vient ''peccatum''"],
    ["que les ''délit'' s sont exceptés du pardon", "que les ''délits'' sont exceptés du pardon"],
    ["Rom. 5, 18", "Rom. 5, 16"],
    ["à celui qui en étai possesseur", "à celui qui en était possesseur"],
    ["de la graisse des autres, animaux purs", "de la graisse des autres animaux purs"],
    ["Id. 8, 2,14", "Id. 8, 2, 14"],
    ["Ib, 4, 5", "Ib. 4, 5"],
    ["le don de sort sacrifice pacifique", "le don de ''son'' sacrifice pacifique"],
    ["dans les deux passages ? Y aurait-il", "dans les deux passages ? y aurait-il"],
    ["devant le voile on parle bien", "devant le voile : on parle bien"],
    ["si c’est l’autel de l'''encens''; et quand", "si c’est l’autel de l’''encens''; et quand"],
    ["que les rues s’accomplirent", "que les rites s’accomplirent"],
    ["au prêtre quia reçu l’onction", "au prêtre qui a reçu l’onction"],
    ["|8, 15, 28]]", "|Lev. 8, 15, 28]]"],
    ["Exo. 19, 24", "Exo. 19, 21"],
    ["ce qu’il avait dit antérieurement", "ce qu’il avait ''dit'' antérieurement"],
    ["honoré du sacerdoce ; pourquoi en remplit-il", "honoré du sacerdoce, pourquoi en remplit-il"],
    ["le fils de Navé est appelé Jésus", "le fils de Navë ⟦sic⟧ est appelé Jésus"],
    ["ce surnom lui l’ut donné", "ce surnom lui fut donné"],
    ["« Vous serez assis, leur dit-il", "« Vous ''serez assis'', leur dit-il"],
    ["elle dit s’asseoir, dans le sens d’habiter, demeurer.", "elle dit ''s’asseoir'', dans le sens ''d’habiter, demeurer''."],
    ["que Séméï s’assit trois ans", "que Séméï ''s’assit'' trois ans"],
    ["constamment assis sur un siège, sans le quitter", "constamment ''assis sur un siège'', sans le quitter"],
    ["permis de dire Il appela la ''jeunesse''", "permis de dire : Il appela la ''jeunesse''"],
    ["Car en disant : Il appela la vieillesse d’Israël", "Car en disant : Il appela la ''vieillesse'' d’Israël"],
    ["Il eût été plus court et peut-être", "Il eût été plus cout ⟦sic⟧ et peut-être"],
    ["Il appela les anciens d’Israël.", "Il appela les ''anciens'' d’Israël."],
    ["à la fin : pour le péché ; et l’agneau seul", "à la fin : ''pour le péché'' ; et l’agneau seul"],
    ["et après ces, mots", "et après ces mots"],
    ["voici te motif", "voici le motif"],
    ["Ib, 6, 19", "Ib. 6, 19"],
    ["nique la poitrine elle-même", "ni que la poitrine elle-même"],
    ["et paît en remplir le ministère", "et pût en remplir le ministère"],
    ["et le prêtre, priera pour lui", "et le prêtre priera pour lui"],
    ["n’est pas générale elle a seulement", "n’est pas générale : elle a seulement"],
    ["Lev. 4, 36", "Lev. 4, 35"],

    // ── p490-494 ──
    ["c’est ''quatre'' qu’il faut lise, et ainsi du reste", "c’est ''quatre'' qu’il faut lire, et ainsi du reste"],
    ["Cela veut-il dire : « Il mit les graisses qui sont sur les poitrines ?", "Cela veut-il dire : Il mit les graisses qui sont sur les poitrines ?"],
    ["L’Écriture néanmoins garde-le silence", "L’Écriture néanmoins garde le silence"],
    ["le feu sortit de, l’endroit où était l’Arche du témoignage Car Dieu", "le feu sortit de l’endroit où était l’Arche du témoignage ? Car Dieu"],
    ["''Sur la traduction du mot'' ἐξεστη.", "''Sur la traduction du mot'' ἐξέστη."],
    ["et Aaron enleva la poitrine et l’épaule droite, comme il avait le droit", "et Aaron enleva la ''poitrine'' et ''l’épaule droite'', comme il avait le droit"],
    ["au singulier, et dit la poitrine ; il s’agit", "au singulier, et dit la ''poitrine'' ; il s’agit"],
    ["« Le serviteur qui ne connaît par la volonté de son maître", "« Le serviteur qui ne connaît pas la volonté de son maître"],
    ["connaît la volonté de « son maître, et qui fait des choses dignes de « châtiment, sera battu rudement", "connaît la volonté de son maître, et qui fait des choses dignes de châtiment, sera battu rudement"],
    ["la mort de Nadabet d’Abiu", "la mort de Nadab et d’Abiu"],
    ["parce que la crainte de lui, déplaire a été sanctionnée", "parce que la crainte de lui déplaire a été sanctionnée"],
    ["la mort des fils d’Aaron ne dût point être l’objet d’un deuil", "la mort des fils d’Aaron ne dût point être l’ojet ⟦sic⟧ d’un deuil"],
    ["Lev. 10, 6-7]]", "Lev. 10, 6, 7]]"],
    ["que le tabernacle duc témoignage désigne ici", "que le ''tabernacle du témoignage'' désigne ici"],
    ["l’exercice de leurs fonctions, la défense devait être levée", "l’exercice de leurs fontions ⟦sic⟧, la défense devait être levée"],
    ["''Soins donnés aux portions", "''Noms donnés aux portions"],
    ["en grec ''ἀφαιρέμα''", "en grec ''ἀφαίρεμα''"],
    ["et fait ''τῶν σωτηρίων'' génitif pluriel ; et ''salutare'' se rend par ''σωτἡριον''", "et fait ''τῶν σωτηριῶν'' au génitif pluriel ; et ''salutare'' se rend par ''σωτήριον''"],
    ["''Sur la part réservée da les sacrifices", "''Sur la part réservée dans les sacrifices"],
    ["réservées aux prêtres, en est quelques-unes", "réservées aux prêtres, il en est quelques-unes"],
    ["leur a fait connaître par l’intermédiaire Moïse", "leur a fait connaître par l’intermédiaire ⟦sic⟧ Moïse"],
    ["je mange aujourd’hui.l'hostie offerte pour le péché", "je mange aujourd’hui l’hostie offerte pour le péché"],
    ["fut le premier offert en ce premier, jour, dès le début", "fut le premier offert en ce premier jour, dès le début"],
    ["dut se faire pour le péché Ne posa-t-il", "dut se faire pour le péché ? Ne posa-t-il"],
    ["selon que Dieu me l’a ordonné » Il est hors de doute", "selon que Dieu me l’a ordonné. » Il est hors de doute"],
    ["« On n’a point « porté du sang de l’hostie", "« On n’a point porté du sang de l’hostie"],
    ["et ferait connaître qu’ils né seront point offerts", "et ferait connaître qu’ils ne seront point offerts"],
    ["Le grec porte ici ''ζωογονούντα''", "Le grec porte ici ''ζωογονοῦντα''"],
    ["Car ''ζωογονούντων'' ne signifie pas", "Car ''ζωογονοῦντα'' ne signifie pas"],
    ["et non des veufs.", "et non des œufs."],
    ["Id. 10, 14,3]]", "Id. 10, 14, 3]]"],
    ["et elle n’entrera point dans le sanctuaire ? », De quel sanctuaire", "et elle n’entrera point dans le sanctuaire ? » De quel sanctuaire"],
    ["au-delà – du voile", "au-delà du voile"],

    // ── p495 ──
    ["et d’entrer dans le sanctuaire.", "et d’entrer dans le santuaire ⟦sic⟧."],
    ["et à la naissance d’une fille, quatre-vingts.", "et à la naissance d’une fille, quatre-vingt ⟦sic⟧."],
    ["'''2.''' De l’offrande des femmes au jour de leur purification. – «", "'''2.''' ''De l’offrande des femmes au jour de leur purification''. – «"],
    ["offert es holocauste ; et pour le péché, le petit", "offert en holoscaute ⟦sic⟧ ; et pour le péché, le petit"],
    ["et l’autre « pour le péché ; et le prêtre priera", "et l’autre pour le péché ; et le prêtre priera"],
    ["elle prendra (''etaccipiet'') deux tourterelles", "elle prendra (''et accipiet'') deux tourterelles"],
    ["sans embarras : elle prendra deux tourterelles ou deux petits de colombe », l’un pour l’holocauste", "sans embarras : « elle prendra deux tourterelles ou deux petits de colombe, » l’un pour l’holocauste"],
    ["et l’autre pour le péché.3.''Suite''. – Mais pour quel péché ?", "et l’autre ''pour le péché''.\n'''3.''' ''Suite''. – Mais pour quel péché ?"],
    ["non l’enfant qu’elle a mis monde ?", "non l’enfant qu’elle a mis monde ⟦sic⟧ ?"],
    ["aucun effet à l’égard des enfants ?", "aucun effet à l’égard des enfans ⟦sic⟧ ?"],
    ["'''4.''' Suite. – Si quelqu’un", "'''4.''' ''Suite''. – Si quelqu’un"],
    ["convaincu d’erreur parle récit de l’Évangile", "convaincu d’erreur par le récit de l’Évangile"],
    ["qui prescrit l’oblation de deux tourterelles ou de deux petits de colombe", "qui prescrit l’oblation de deux tourterlles ⟦sic⟧ ou de deux petits de colombe"],
    ["Ainsi ce divin Sauveur, voulut recevoir", "Ainsi ce divin Sauveur voulut recevoir"],

    // ── p496 ──
    ["Quoi qu’il en soit, c’est donc la difformité", "Quoiqu’il en soit, c’est donc la difformité"],
    ["qui le rendait. Facilement reconnaissable", "qui le rendait facilement reconnaissable"],
    ["''ἄμῶμον'' sans tache", "''ἄμωμον'' sans tache"],
    ["employer ''σπιλον'' pour désigner", "employer ''σπῖλον'' pour désigner"],
    ["ni ''μῶμον'', ni ''σπιλον'' mais ''ἁφὴν''", "ni ''μῶμον'', ni ''σπῖλον'' mais ''ἁφὴν''"],
    ["''cicatrice de marque''; cela veut dire", "''cicatrice de marque'' ; cela veut dire"],
    ["(Ib, 13, 4.)", "(Ib. 13, 4.)"],
    ["L’Écrituredit plus loin", "L’Écriture dit plus loin :"],
    ["les Latins on rendut plus haut", "les Latins ont rendu plus haut"],
    ["''σημασίας''", "''σημασίαν''"],

    // ── p497 ──
    ["quant à la conjonction et, c’est un mot", "quant à la conjonction ''et'', c’est un mot"],
    ["L’Écriture parait donc poser", "L’Écriture paraît donc poser"],
    ["[[Bible_Crampon_1923|Ib, 6]]", "[[Bible_Crampon_1923|Ib. 6]]"],
    ["sept jours ; delà les prescriptions", "sept jours ; de là les prescriptions"],
    ["sa couleur né, diffère plus", "sa couleur ne diffère plus"],
    ["semblable au reste de la couleur Ce n’était", "semblable au reste de la couleur. Ce n’était"],
    ["seulement le signe <ref>", "seulement le signe<ref>"],
    ["en d’autres, termes, si l’homme", "en d’autres termes, si l’homme"],
    ["la dépression, de la peau", "la dépression de la peau"],
    // Le scan imprime bien « 9-7 ». Le correctif Wikisource « 9-10 » n’est pas
    // une donnée de l’édition : conserver la leçon source et signaler l’anomalie.
    ["{{corr|9-7|9-10}}", "9-7 ⟦sic⟧"],
    ["On lit ensuite « : Si le toucher", "On lit ensuite : « Si le toucher"],
    ["la particule et de cette dernière phrase", "la particule ''et'' de cette dernière phrase"],

    // ── p498 ──
    ["de l’état sain « de chair vive en cicatrice", "de l’état sain de chair vive en cicatrice"],
    ["Voici la construction régulière:« Elle", "Voici la construction régulière : « Elle"],
    ["avait un chevelure noire", "avait un chevelure ⟦sic⟧ noire"],
    ["dans la peau est« elle de cette couleur", "dans la peau est-elle de cette couleur"],
    ["le prêtre le rendra impur <ref>", "le prêtre le rendra impur<ref>"],
    ["Ceci parait signifier", "Ceci paraît signifier"],
    ["au défaut blanc, de la peau", "au défaut blanc de la peau"],
    ["différentes, ajouté :", "différentes, ajoute :"],
    ["Id. 16,17]]", "Id. 16, 17]]"],
    ["''ébranlement θραῦσμά''", "''ébranlement θραῦσμα''"],
    ["ne sont pas des, vêtements", "ne sont pas des vêtements"],
    ["''ergasmeno ἐργασμἐνῳ δέρματι''", "''ἐργασμένῳ δέρματι''"],
    ["dans le jour ou l’on travaille", "dans le jour où l’on travaille"],
    ["[[Bible_Crampon_1923/1 Samuel#20|1Sa. 20, 19.]]", "[[Bible_Crampon_1923/1 Samuel#20|I Rois, XX, 19.]]"],

    // ── p499 ──
    ["les Grecs nomment ''σκεῦος'' terme général", "les Grecs nomment ''σκεῦος'', terme général"],
    ["L’expression ''ἀγγεῖον'' un autre sens", "L’expression ''ἀγγεῖον'' a un autre sens"],
    ["faut-il entendre ces paroles.« Il priera", "faut-il entendre ces paroles : « Il priera"],
    ["le grec ''ἱλαστἠρἰον''", "le grec ''ἱλαστήριον''"],
    ["Le sens le plus convenable est donc, celui-ci. Le prêtre", "Le sens le plus convenable est donc celui-ci : Le prêtre"],
    ["''το πνεῦμα τὸ ἅγιον''", "''τὸ πνεῦμα τὸ ἅγιον''"],
    ["favorable aux choses sanctifiées au Seigneur", "favorable aux choses ''sanctifiées'' au Seigneur"],

    // ── p500 ──
    ["au milieu de leur impureté <ref>", "au milieu de leur impureté<ref>"],
    ["d’apaiser le, Seigneur", "d’apaiser le Seigneur"],
    ["ce que nous avens dit", "ce que nous avons dit"],
    ["mais cette prescription – ne prouve", "mais cette prescription ne prouve"],
    ["or, des là que le veau", "or, dès là que le veau"],
    ["entre.cesdeux boucs", "entre ces deux boucs"],
    ["pour le Saint du Saint<ref>", "pour le ''Saint du Saint''<ref>"],
    ["Il priera dans le Saint du Saint, expression", "Il priera dans le ''Saint du Saint'', expression"],
    ["la partie du sanctuaire, au-delà", "la partie du ''sanctuaire'', au-delà"],
    ["''τὸ ἅγιον πνεῦμα τοῦ ἁγίου θεολῦ''", "''τὸ ἅγιον πνεῦμα τοῦ ἁγίου θεοῦ''"],
    ["Ou plutôt « il priera n’est-il pas mis", "Ou plutôt « il priera » n’est-il pas mis"],
    ["d’être son propre prêtre, élit veut", "d’être son propre prêtre, et il veut"],
    ["[[Bible_Crampon_1923/1 Rois#12|1Ro. 12, 28-39]]", "[[Bible_Crampon_1923/1 Rois#12|III Rois, XII, 25-30]]"],

    // ── p501 ──
    ["ces paroles de Dieu ; à propos", "ces paroles de Dieu, à propos"],
    ["de manger du sang « L’âme", "de manger du sang : « L’âme"],
    ["avec moi dans « le paradis", "avec moi dans le paradis"],
    ["Je n’estime pas mon âme plus précieuse", "Je n’estime pas mon ''âme'' plus précieuse"],
    ["plus précieuse que moi <ref>", "plus précieuse que moi<ref>"],
    ["le sang prie pouf le sang", "le sang prie pour le sang"],
    ["ce.seraitd'imaginer", "ce serait d’imaginer"],
    ["[[Bible_Crampon_1923/Hébreux#10|Heb. 10, 4]]", "[[Bible_Crampon_1923/Hébreux#10|Hébr. X, 4]]"],
    ["De là cette parole:« La pierre", "De là cette parole : « La pierre"],
    ["[[Bible_Crampon_1923/1_Corinthiens#10|1Co. 10, 4]]", "[[Bible_Crampon_1923/1_Corinthiens#10|I Cor. X, 4]]"],
    ["Ainsi le sang s’appelle-t-il âme dans le langage", "Ainsi le sang s’appelle-t-il ''âme'' dans le langage"],

    // ── p502 ──
    ["ne soit que du sang cette erreur", "ne soit que du sang : cette erreur"],
    ["l’âme est signifie par le sang", "l’âme est signifiée par le sang"],
    ["Il est encore écrit«", "Il est encore écrit : «"],
    ["Aux termes de l’Écriture la récompense", "Aux termes de l’Écriture, la récompense"],
    ["vous n’aurez point là vie en vous", "vous n’aurez point la vie en vous"],
    ["(Ib. 18, 7-8.)", "(Ib. XVIII, 7-8.)"],
    ["1° ''avec, la mère et la belle mère''", "1° ''avec la mère et la belle mère''"],
    ["(Ib. 18, 9.)", "(Ib. XVIII, 9.)"],
    ["l’Écriture, ajoute ce qui suit", "l’Écriture ajoute ce qui suit"],

    // ── p503 ──
    ["(Ib. 18, 14.)", "(Ib. XVIII, 14.)"],
    ["qui.défendl'union", "qui défend l’union"],
    ["L’Écriture semble donc parler (les personnes", "L’Écriture semble donc parler des personnes"],
    ["<ref>[[Bible_Crampon_1923/Deutéronome#25|Deu. 25, 5]]</ref> en rapprochant", "<ref>[[Bible_Crampon_1923/Deutéronome#25|Deut. XXV, 5.]]</ref> En rapprochant"],
    ["Moïse avait « permis", "Moïse avait permis"],
    ["de leur « cœur", "de leur cœur"],
    ["(Ib. 18, 17.)", "(Ib. XVIII, 17.)"],
    ["la honte de la femme et e sa fille", "la honte de la femme et de sa fille"],
    ["(Ib. 18, 17, 18.)", "(Ib. XVIII, 17, 18.)"],
    ["rapprochées parle sang", "rapprochées par le sang"],
    ["(Ib. 18, 19.)", "(Ib. XVIII, 19.)"],

    // ── p504 ──
    ["les péchés.quiconstituent", "les péchés qui constituent"],
    ["le prophète mentionné la faute", "le prophète mentionne la faute"],
    ["(Ib. 18, 20.)", "(Ib. XVIII, 20.)"],
    ["(Ib. 18, 21.)", "(Ib. XVIII, 21.)"],
    ["au lieu de ''douleuein'', le grec porte ici ''λατρεύειν''", "au lieu de ''δουλεύειν'', le grec porte ici ''λατρεύειν''"],
    ["en grec par ''douleuein'', et non par ''λατρεύειν''", "en grec par ''δουλεύειν'', et non par ''λατρεύειν''"],
    ["dans le sens de ''douleuein'' est point dû", "dans le sens de ''λατρεύειν'', n’est point dû"],
    ["(Ib. 18, 25.)", "(Ib. XVIII, 25.)"],
    ["parce qu’ils ; sont un sujet", "parce qu’ils sont un sujet"],
    ["(Ib. 19, 11.)", "(Ib. XIX, 11.)"],
    ["le vol ne fait tort à personnel", "le vol ne fait tort à personne ?"],
    ["je ne sais sil est possible", "je ne sais s’il est possible"],
    ["que Joseph cri accusant faussement", "que Joseph en accusant faussement"],

    // ── p505 ──
    ["quand on l’ait du tort au prochain", "quand on fait du tort au prochain"],
    ["serait d’une facile solution, si nous, ne considérions", "serait d’une facile solution, si nous ne considérions"],
    ["d’après la définition que nous avons donné, le vol", "d’après la définition que nous avons donné ⟦sic⟧, le vol"],
    ["(Ib. 19, 13.)", "(Ib. XIX, 13.)"],
    ["(Ib. 19, 17,18.)", "(Ib. XIX, 17, 18.)"],
    ["n’est pas punie pour.lemal qui se commet", "n’est pas punie pour le mal qui se commet"],
    ["d’oublier les toits d’autrui", "d’oublier les torts d’autrui"],
    ["mais consulté plutôt l’avantage, de celui", "mais consulte plutôt l’avantage de celui"],
    ["(Ib. 19, 28.)", "(Ib. XIX, 28.)"],

    // ── p506 ──
    ["''A l’occasion d’une âme''", "''À l’occasion d’une âme''"],
    ["(Ib. 20, 5.)", "(Ib. XX, 5.)"],
    ["(Ib. 20, 10.)", "(Ib. XX, 10.)"],
    ["''qu’ils meurent'': « ces derniers mots", "''qu’ils meurent'' : » ces derniers mots"],
    ["Si l’on doit.respecterla femme", "Si l’on doit respecter la femme"],
    ["(Ib. 20, 16.)", "(Ib. XX, 16.)"],
    ["la femme et la « bête", "la femme et la bête"],
    ["un vent mauvais une mer en courroux", "un vent mauvais, une mer en courroux"],
    ["un animal peut-être coupable", "un animal peut-être ⟦sic⟧ coupable"],
    ["(Ib. 20, 17.)", "(Ib. XX, 17.)"],
    ["pour ; il s’unit à elle", "pour : il s’unit à elle"],
    ["\nV 20\n", "\n"],
    ["(Ib. 20, 20.)", "(Ib. XX, 20.)"],
    ["avec sa Parente", "avec sa parente"],

    // ── p507 ──
    ["la succession de leurs parents.\n", "la succession de leurs parents ?\n"],
    ["'''2.''' (Ib. XX. 25.)", "'''2.''' (Ib. XX, 25.)"],
    ["\nV 27\n", "\n"],
    ["(Ib. 20, 27.)", "(Ib. XX, 27.)"],
    ["(Ib. 21, 7.)", "(Ib. XXI, 7.)"],
    ["nous lisions :« il présentera", "nous lisions : « il présentera"],
    ["Ils ne prendront point de « femme déshonorée", "Ils ne prendront point de femme déshonorée"],
    ["(Ib. 21, 10.)", "(Ib. XXI, 10.)"],
    ["du quel a été répandue", "du quel ⟦sic⟧ a été répandue"],
    ["''oleochristo''", "''oleo christo''"],
    ["(Ib, 21, 10-11.)", "(Ib. XXI, 10-11.)"],
    ["rendu au, jour de la résurrection", "rendu au jour de la résurrection"],

    // ── p508 ──
    ["dans un cadavre le ; sang", "dans un cadavre le sang"],
    ["(Ib. 21, 12.)", "(Ib. XXI, 12.)"],
    ["le préservait de ce danger mais, en ce qui concerne", "le préservait de ce danger : mais, en ce qui concerne"],
    ["d’une réponse analogue \\f + ft 2 Rétract. ch. 55. n. 9</ref>", "d’une réponse analogue<ref>II Rétract. ch. 55, n. 9.</ref>"],
    ["(Ib. 21, 11.)", "(Ib. XXI, 11.)"],
    ["funérailles de son père, Mais, demandera-t-on", "funérailles de son père. Mais, demandera-t-on"],
    ["(Ib. 21, 15.)", "(Ib. XXI, 15.)"],
    ["cet ordre à Moïse « Tu le sanctifieras", "cet ordre à Moïse : « Tu le sanctifieras"],

    // ── p509 ──
    ["les sacrements qui tombent sous nos sens Aurait-on", "les sacrements qui tombent sous nos sens ? Aurait-on"],
    ["eût été : sanctifié d’une manière invisible", "eût été sanctifié d’une manière invisible"],
    ["Nous ne pouvons dès lors mettre en doute sa sainteté : et cependant", "Nous ne pouvons dès lors mettre en doute sa sainteté ; et cependant"],
    ["qu’elle lui ait, été conférée", "qu’elle lui ait été conférée"],
    ["du larron en croix,<ref>", "du larron en croix<ref>"],
    ["fit entendre ces paroles ; « Tu seras", "fit entendre ces paroles : « Tu seras"],
    ["Il suit delà que", "Il suit de là que"],
    ["ne peut-être aucunement sanctifié", "ne peut être aucunement sanctifié"],
    ["(Ib. 22, 1, 2, 3.)", "(Ib. XXII, 1, 2, 3.)"],
    ["(Ib. 22, 4.)", "(Ib. XXII, 4.)"],
    ["(Ib. 24, 15.)", "(Ib. XXIV, 15.)"],

    // ── p510 ──
    ["du Seigneursont.deuxchoses différentes", "du Seigneur sont deux choses différentes"],
    ["l’Écriture disant : «''mais'' que celui", "l’Écriture disant : « ''mais'' que celui"],
    ["(Ib. 24, 17.)", "(Ib. XXIV, 17.)"],
    ["cette parole du Seigneur. « Ne craignez", "cette parole du Seigneur : « Ne craignez"],
    ["(Ib. 25, 2-7.)", "(Ib. XXV, 2-7.)"],
    ["tu en recueilleras le fruit du rapt six ans", "tu en recueilleras le fruit durant six ans"],
    ["tu tailleras aussi ta.vigneet tu en recueilleras", "tu tailleras aussi ta vigne et tu en recueilleras"],
    ["ainsi, dans.cecas, la taille", "ainsi, dans ce cas, la taille"],
    ["Car si une vigne ne doit pas être taillée, elle, ne doit pas", "Car si une vigne ne doit pas être taillée, elle ne doit pas"],

    // ── p511 ──
    ["(Ib. 25, 23.)", "(Ib. XXV, 23.)"],
    ["''la profanation'';", "''la profanation'' ;"],
    ["''d’une manière irrévocable''(''in confirmationem'')", "''d’une manière irrévocable'' (''in confirmationem'')"],
    ["Mais il a y de l’obscurité", "Mais il a y ⟦sic⟧ de l’obscurité"],
    ["(Ib, 25, 24.)", "(Ib., XXV, 24.)"],
    ["par ce qu’il leur a donné un pays", "par ce ⟦sic⟧ qu’il leur a donné un pays"],
    ["[[Bible_Crampon_1923/Lévitique#23|Lev. 23, 2]]", "Jér. XXIII, 24."],
    ["(Ib. 25, 24.)", "(Ib. XXV, 24.)"],
    ["(Ib. 26, 11.)", "(Ib. XXVI, 11.)"],
    ["Car il n’est par un être vivant", "Car il n’est pas un être vivant"],
    ["[[Bible_Crampon_1923/Isaïe#57|Isa. 57, 16]]", "Isaïe, LVII, 16."],

    // ── p512 ──
    ["(Ib. 26, 33, 34.)", "(Ib. XXVI, 33, 34.)"],
    ["''Sens de ces paroles le glaive vous anéantira''", "''Sens de ces paroles : le glaive vous anéantira''"],
    ["Que signifie ce pas sage ?", "Que signifie ce pas sage ⟦sic⟧ ?"],
    ["cette « pression : « il vous consumera »", "cette expression : « il vous consumera »"],
  ],
  LABEL_SIC: [],
}
