// Livre IV — Questions sur les Nombres. Pages 512 (s2) - 537 (s1).
export default {
  NORM: [[/nué e/g, "nuée"]],
  cle: "nombres", fichier: "Nombres_draft",
  titre: "Livre quatrième — Questions sur les Nombres",
  titreCourt: "Nombres",
  de: 512, a: 537, debutSection: "s2", finSection: "s1",
  CORR: [
    ["nué e", "nuée"],
    // ── p512 ──
    ["(Nomb. 1, 1-14)", "(Nomb. I, 1-14)"],
    ["Χιλιου", "Χίλιοι"],
    ["''écatontarques''; centurions", "''écatontarques'', centurions"],
    ["non pas. un millier d’Hommes", "non pas un millier d’hommes"],
    // ── p513 ──
    ["tout cela parait plutôt", "tout cela paraît plutôt"],
    ["(Ib. 1, 51.)", "(Ib. I, 51.)"],
    ["''ἀλλὀθυλος''", "''ἀλλόφυλος''"],
    ["(Ib. 3, 5-7.)", "(Ib. III, 5-7.)"],
    // ── p514 ──
    ["tentes des enfants d’Israël\n", "tentes des enfants d’Israël ?\n"],
    ["(Ib. 3, 10.)", "(Ib. III, 10.)"],
    ["« L’étranger, qui y touchera sera puni de mort.", "« L’étranger qui y touchera, sera puni de mort."],
    ["Lev. 6, 18.", "Lév. VI, 18."],
    ["(Ib. 3, 12-31.)", "(Ib. III, 12-31.)"],
    ["(Ib. 4, 7.)", "(Ib. IV, 7.)"],
    ["(Ib. 4, 11.)", "(Ib. IV, 11.)"],
    ["(Ib. 5, 6, 7, 8.)", "(Ib. V, 6, 7, 8.)"],
    // ── p515 ──
    ["qu’il n’est, question des proches", "qu’il n’est question des proches"],
    ["« Le délit qui est rendu au Seigneur, « sera pour le prêtre.", "« Le délit qui est rendu au Seigneur, sera pour le prêtre."],
    ["(Ib. 5, 6, 7.)", "(Ib. V, 6, 7.)"],
    ["Exo. 22, 1, 4", "Ex. XXII, 1, 4"],
    ["Il est possible, en effet, – qu’un homme", "Il est possible, en effet, qu’un homme"],
    ["et ce qui prouve – qu’il y a péché", "et ce qui prouve qu’il y a péché"],
    ["parmi, les hommes", "parmi les hommes"],
    ["péchés ordinaires, à l’homme", "péchés ordinaires à l’homme"],
    ["(Ib. 5, 21.)", "(Ib. V, 21.)"],
    ["ceux qui jureront Que pareille chose", "ceux qui jureront : Que pareille chose"],
    ["(Ib. 6, 14-17.)", "(Ib. VI, 14-17.)"],
    // ── p516 ──
    ["''la victime immolée pour le péché'' plus loin", "''la victime immolée pour le péché''; plus loin"],
    ["2Co. 5, 21", "II Cor. V, 21"],
    ["Lev. 6, 16-17.", "Lév. VI, 16, 17."],
    ["(Ib. 8, 24.)", "(Ib. VIII, 24.)"],
    ["(Ib. 8, 24-26.)", "(Ib. VIII, 24-26.)"],
    ["(Ib. 9, 6.)", "(Ib. IX, 6.)"],
    ["Israélite, a qui survenait", "Israélite, à qui survenait"],
    ["(Ib. 9, 15-23.)", "(Ib. IX, 15-23.)"],
    ["— <ref>[[Bible_Crampon_1923/Lévitique#9|Lev. 9, 15]]</ref> « Et au jour", "— « Et au jour"],
    ["la maison du témoignage ; et depuis le soir", "la maison du témoignage<ref>[[Bible_Crampon_1923/Lévitique#9|Lév. IX, 15]]</ref> ; et depuis le soir"],
    // ── p517 ──
    ["[[Bible_Crampon_1923|Id. 16]]", "[[Bible_Crampon_1923|Ib. 16]]"],
    ["[[Bible_Crampon_1923|Id. 17]]", "[[Bible_Crampon_1923|Ib. 17]]"],
    ["[[Bible_Crampon_1923|Id. 18]]", "[[Bible_Crampon_1923|Ib. 18]]"],
    ["[[Bible_Crampon_1923/Lévitique#9|Lev. 9, 19]]", "[[Bible_Crampon_1923/Lévitique#9|Ib. 19]]"],
    ["[[Bible_Crampon_1923|Id. 20]]", "[[Bible_Crampon_1923|Ib. 20]]"],
    ["Psa. 21, 17", "Ps. XXI, 17"],
    ["Isa. 53, 7", "Isaïe, LIII, 7"],
    // ── p518 ──
    ["pendant le jour, où si elle", "pendant le jour, ou si elle"],
    ["[[Bible_Crampon_1923/Lévitique#9|Lev. 9, 21.]]", "[[Bible_Crampon_1923/Lévitique#9|Lév. IX, 21.]]"],
    ["[[Bible_Crampon_1923/Lévitique#9|Lev. 9, 22.]]", "[[Bible_Crampon_1923/Lévitique#9|Lév. IX, 22.]]"],
    ["qu’on ne comprit les nuits", "qu’on ne comprît les nuits"],
    ["lorsqu’une nuée abondante couvrira » en d’autres termes", "lorsqu’une nuée abondante couvrira, » en d’autres termes"],
    ["reçu parla main de Moïse", "reçu par la main de Moïse"],
    ["(Ib. 10, 7.)", "(Ib. X, 7.)"],
    // ── p519 ──
    ["(Ib. 11, 17.)", "(Ib. XI, 17.)"],
    ["1Co. 2, 11", "I Cor. II, 11"],
    ["[[Bible_Crampon_1923|Id. 12]]", "[[Bible_Crampon_1923|Ib. 12]]"],
    ["par la grâce, divine", "par la grâce divine"],
    ["2Ro. 2, 15", "IV Rois, II, 15"],
    ["(Ib. 11, 21-23.)", "(Ib. XI, 21-23.)"],
    ["mettre en doute, sa toute-puissance", "mettre en doute sa toute-puissance"],
    ["Nom. 20,\n10", "Nomb. XX, 10"],
    ["Ib, 11, 23", "Ib. XI, 23"],
    ["Luc. 1, 34", "Luc, I, 34"],
    ["[[Bible_Crampon_1923|Id. 35]]", "[[Bible_Crampon_1923|Ib. 35]]"],
    ["[[Bible_Crampon_1923|Id. 18-20]]", "[[Bible_Crampon_1923|Ib. 18-20]]"],
    // ── p520 ──
    ["Nom. 20, 10-11", "Nomb. XX, 10, 11"],
    ["[[Bible_Crampon_1923|Id. 12.]]", "[[Bible_Crampon_1923|Ib. 12.]]"],
    ["Ici ; au contraire", "Ici, au contraire"],
    ["(Ib. 12, 1.)", "(Ib. XII, 1.)"],
    ["femme de Moise", "femme de Moïse"],
    ["2Ch. 24, 9-14", "II Paralip. XXIV, 9-14"],
    ["(Ib. 13, 18-26.)", "(Ib. XIII, 18-26.)"],
    ["nous dit qu’ils ont pénétré Comment encore – ont-ils", "nous dit qu’ils ont pénétré ? Comment encore ont-ils"],
    ["souvenir de cet évènement", "souvenir de cet événement"],
    ["un Terrain légèrement incliné", "un terrain légèrement incliné"],
    ["Nom. 13, 23-24", "Nomb. XIII, 23, 24"],
    ["(Ib. 13, 33.)", "(Ib. XIII, 33.)"],
    ["(Ib. 14, 9.)", "(Ib. XIV, 9.)"],
    // ── p521 ──
    ["le peuplé né craignit", "le peuple ne craignît"],
    ["le Seigneur est en nous ne les craignez point", "le Seigneur est en nous : ne les craignez point"],
    ["«car le temps", "« car le temps"],
    ["sa providence, accordé à l'impie", "sa providence, accorde à l'impie"],
    ["prospérité.et de triomphe", "prospérité et de triomphe"],
    ["Ils ne disent pas « Le temps", "Ils ne disent pas : « Le temps"],
    ["(Ib. 15, 24-29.)", "(Ib. XV, 24-29.)"],
    ["donne lieu à cette question Qu’entend-on", "donne lieu à cette question : Qu’entend-on"],
    ["le péché pour, lui-même", "le péché pour lui-même"],
    ["(Ib. 15, 30-31.)", "(Ib. XV, 30, 31.)"],
    ["foulé aux pieds ses commandements cette âme", "foulé aux pieds ses commandements : cette âme"],
    ["Prov, 18, 3", "Prov. XVIII, 3"],
    ["Psa. 50, 19", "Ps. L, 19"],
    // ── p522 ──
    ["Dieu<ref>[[Bible_Crampon_1923/Nombres#15|Nom. 15, 30]]</ref>", "Dieu<ref>[[Bible_Crampon_1923/Nombres#15|Nomb. XV, 30]]</ref>"],
    ["peuple <ref>[[Bible_Crampon_1923/Nombres#15|Nom. 15, 30]]</ref>", "peuple <ref>[[Bible_Crampon_1923/Nombres#15|Nomb. XV, 30]]</ref>"],
    ["Jac. 4, 6", "Jacq. IV, 6"],
    ["[[Bible_Crampon_1923|Id. 31]]", "[[Bible_Crampon_1923|Ib. 31]]"],
    ["elle:» par conséquent", "elle : » par conséquent"],
    ["Sir. 6, 36", "Eccli. VI, 36"],
    ["(Ib. 16, 13, 14.)", "(Ib. XVI, 13, 14.)"],
    ["Gal. 4,15", "Gal. IV, 15"],
    ["(Ib. 26, 20, 21.)", "(Ib. XVI, 20, 21.)"],
    ["Gen. 7, 15", "Gen. VII, 15"],
    ["[[Bible_Crampon_1923|Id. 19, 12]]", "[[Bible_Crampon_1923|Ibid. XIX, 12]]"],
    ["Ex0. 19, 20", "Ex. XIX, 20"],
    ["scission et de là révolte", "scission et de la révolte"],
    // ── p523 ──
    ["Mat. 13, 30, 43.", "Matt. XIII, 30, 43."],
    ["(Ib. 16, 30.)", "(Ib. XVI, 30.)"],
    ["''khasmati''", "''χάσματι''"],
    ["''phasmati''", "''φάσματι''"],
    ["(Ib. 16, 32,33.)", "(Ib. XVI, 32, 33.)"],
    ["vivants aux « enfers", "vivants aux enfers"],
    ["acceptions très-différents", "acceptions très-différentes"],
    ["2Pi. 2, 4", "II Pierre, II, 4"],
    ["Eph. 2, 2.", "Eph. II, 2."],
    ["(Ib. 16, 36-40.)", "(Ib. XVI, 36-40.)"],
    ["et sème là ce feu étranger parce", "et sème là ce feu étranger : parce"],
    ["sanctifiés parleurs âmes", "sanctifiés par leurs âmes"],
    ["a dit parla main de Moïse", "a dit par la main de Moïse"],
    // ── p524 ──
    ["un avertissement, à Israël", "un avertissement à Israël"],
    ["cette offrande à été faite", "cette offrande a été faite"],
    ["a plus clé vertu", "a plus de vertu"],
    ["Exo. 27, 2", "Ex. XXVII, 2"],
    ["Nom. 17, 8", "Nomb. XVII, 8"],
    ["Exo. 26", "Ex. XXVI"],
    ["[[Bible_Crampon_1923|Id. 40, 15.]]", "[[Bible_Crampon_1923|Ib. XL, 15.]]"],
    ["(Ib. 18, 1.)", "(Ib. XVIII, 1.)"],
    ["les péchés des saints ; maison les appelle", "les péchés des saints ; mais on les appelle"],
    ["Lev. 6, 25-26.", "Lév. VI, 25, 26."],
    ["(Ib. 18, 12.)", "(Ib. XVIII, 12.)"],
    ["qui sont « dans leur terre", "qui sont dans leur terre"],
    ["''πρωτογενήματα'', Mais", "''πρωτογενήματα''. Mais"],
    ["''απαρκαἰ''", "''ἀπαρχαί''"],
    ["(Ib. 19, 1-22.)", "(Ib. XIX, 1-22.)"],
    ["l’eau d’expiation''. \n – Nous", "l’eau d’expiation''. – Nous"],
    // ── p525 ──
    ["attendre de lui L’immolation", "attendre de lui. L’immolation"],
    ["le Seigneur a établies quand il disait.", "le Seigneur a établies quand il disait. »"],
    ["le Ciel et la terre", "le ciel et la terre"],
    ["elle eu est une confirmation", "elle en est une confirmation"],
    ["Rom. 8, 3", "Rom. VIII, 3"],
    // ── p526 ──
    ["Psa. 115, 16, 17", "Ps. CXV, 16, 17"],
    ["Jn. 10, 18", "Jean, X, 18"],
    ["ce grand évènement", "ce grand événement"],
    ["Rom. 3, 25", "Rom. III, 25"],
    ["Eph. 1, 7", "Eph. I, 7"],
    ["opérée parle sang du Christ", "opérée par le sang du Christ"],
    ["et il les jet » fera au milieu", "et il les jettera au milieu"],
    ["ce mot de l’Apôtre « Votre vie", "ce mot de l’Apôtre : « Votre vie"],
    ["au peuple, juif", "au peuple juif"],
    ["Col. 3, 3", "Colos. III, 3"],
    ["Psa. 36, 37", "Ps. XXXVI, 37"],
    // ── p527 ──
    ["Rom. 3, 23-24", "Rom. III, 23, 24"],
    ["Act. 10, 44-48", "Act. X, 44-48"],
    ["Rom. 11, 16-24", "Rom. XI, 16-24"],
    ["Amo. 1,3", "Amos, I, 3"],
    ["même après la mort, quant au temps de la vie", "même après la mort, quand⟦sic⟧ au temps de la vie"],
    ["1Th. 5, 19", "I Thess. V, 19"],
    // ── p528 ──
    ["que Peau d’aspersion", "que l’eau d’aspersion"],
    ["leurs cœurs parla foi", "leurs cœurs par la foi"],
    ["Act. 15, 9", "Act. XV, 9"],
    ["(Ib. 19, 16.)", "(Ib. XIX, 16.)"],
    ["(Ib. 20, 11.)", "(Ib. XX, 11.)"],
    ["1Co. 10,4", "I Cor. X, 4"],
    ["(Ib. 20, 13.)", "(Ib. XX, 13.)"],
    ["un Symbole figuratif", "un symbole figuratif"],
    ["Luc. 2, 34.", "Luc, II, 34."],
    ["'''XXXVII.''' (Ib. 20, 17.)", "'''XXXVII.''' (Ib. XX, 17.)"],
    ["'''XXXVIII.''' (Ib. 20, 17.)", "'''XXXVIII.''' (Ib. XX, 17.)"],
    // ── p529 ──
    ["à droite , soit", "à droite, soit"],
    ["à gauche.''", "à gauche."],
    ["(Ib. 20, 24.)", "(Ib. XX, 24.)"],
    ["''antilogias''", "''ἀντιλογίας''"],
    ["(Ib. 21, 2.)", "(Ib. XXI, 2.)"],
    ["Gal 1, 8.", "Gal. I, 8."],
    ["(Ib. 21, 3.)", "(Ib. XXI, 3.)"],
    ["''ἀνεθεμάτισεν''", "''Ἀνατίθημι''"],
    ["(Ib. 21, 13, 14.)", "(Ib. XXI, 13, 14.)"],
    ["dans le désert, est sur les limites", "dans le désert, et sur les limites"],
    ["Tit. 1, 12", "Tite, I, 12"],
    ["Act. 18, 28", "Act. XVII, 28"],
    ["(Ib. 21, 16.)", "(Ib. XXI, 16.)"],
    // ── p530 ──
    ["(Ib. 21, 24,25.)", "(Ib. XXI, 24, 25.)"],
    ["jusqu’à Jaboc et, jusqu’aux", "jusqu’à Jaboc et jusqu’aux"],
    ["Nom. 20, 21.", "Nomb. XX, 21."],
    ["(Ib. 21, 27.)", "(Ib. XXI, 27.)"],
    ["Venez à Esebon", "Venez à Esébon"],
    ["(Ib. 22, 4-6.)", "(Ib. XXII, 4-6.)"],
    ["Batac, roi des Moabites", "Balac, roi des Moabites"],
    ["Gen. 19, 37", "Gen. XIX, 37"],
    ["[[Bible_Crampon_1923|Tb. 25, 2]]</ref>##Rem", "[[Bible_Crampon_1923|Ib. XXV, 2]]</ref>"],
    ["(Ib. 22, 7-41.)", "(Ib. XXII, 7-16.)"],
    ["près de toi etc ?", "près de toi etc. ?"],
    ["Nom. 22, 13", "Nomb. XXII, 13"],
    ["cet évènement eut lieu", "cet événement eut lieu"],
    // ── p531 ──
    ["Luc. 12, 16-20.", "Luc, XII, 16-20."],
    ["(Ib. 22, 12-38.)", "(Ib. XXII, 12-38.)"],
    ["reçu du, Seigneur", "reçu du Seigneur"],
    ["volonté du Seigneur à se sujet", "volonté du Seigneur à ce sujet"],
    ["À quoi, bon", "À quoi bon"],
    ["Et Dieufut animé", "Et Dieu fut animé"],
    ["L’ange, lui parle ensuite", "L’ange lui parle ensuite"],
    ["2Pi. 2, 15.", "II Pierre, II, 15."],
    ["(Ib. 22, 22,32.)", "(Ib. XXII, 22, 32.)"],
    ["Discussion, grammaticale", "Discussion grammaticale"],
    // ── p532 ──
    ["Apo. 11, 9-10", "Apoc. XI, 9, 10"],
    ["Térence, Andr. act. 2, scène. 4.", "Térence, Andr. act. II, scène. 4."],
    ["(Ib. 22, 23-29.)", "(Ib. XXII, 23-29.)"],
    ["L’ânesse ayant vu l’Ange de Dieu", "« L’ânesse ayant vu l’Ange de Dieu"],
    ["s’affaissa, sous Balaam", "s’affaissa sous Balaam"],
    ["1Co. 1,27", "I Cor. I, 27"],
    ["(Ib. 23, 5.)", "(Ib. XXIII, 5.)"],
    ["Jn. 1, 30", "Jean, I, 30"],
    ["Psa. 29,11", "Ps. XXIX, 11"],
    ["[[Bible_Crampon_1923|Id. 9, 10]]", "[[Bible_Crampon_1923|Ib. IX, 10]]"],
    ["Eze. 1, 3 ; 3, 22", "Ézéch. I, 3 ; III, 22"],
    ["(Ib. 25, 4,7,8.)", "(Ib. XXV, 4, 7, 8.)"],
    // ── p533 ──
    ["''παραδειγμά''", "''παράδειγμα''"],
    ["''attache eu haut''", "''attache en haut''"],
    ["''anapexon''", "''ἀνάπηξον''"],
    ["encore Pends##Rem.", "encore ''Pends''."],
    ["je ne vois pis", "je ne vois pas"],
    ["(Ib. 27, 13,14.)", "(Ib. XXVII, 13, 14.)"],
    ["Nom. 20, 12", "Nomb. XX, 12"],
    ["Ci-dessus, quest. XIX.", "Ci-dessus, Quest. XIX."],
    ["comme, d’anciens types", "comme d’anciens types"],
    ["de celte colère divine", "de cette colère divine"],
    ["leu r mort", "leur mort"],
    ["leurs l’onctions", "leurs fonctions"],
    ["(Ib. 27, 18, 19.)", "(Ib. XXVII, 18, 19.)"],
    // ── p534 ──
    ["(Ib. 27, 20.)", "(Ib. XXVII, 20.)"],
    ["Le grec porter", "Le grec porte"],
    ["(Ib. 30, 3.)", "(Ib. XXX, 3.)"],
    ["(Ib. 30, 4-6.)", "(Ib. XXX, 4-6.)"],
    ["et qu’était gardé le silence. :", "et qu’il ait gardé le silence :"],
    ["parce que son père s’y est opposé. Comme", "parce que son père s’y est opposé. » Comme"],
    ["sait en effet, que, les vierges", "sait en effet, que les vierges"],
    ["1Co. 7, 37-38", "I Cor. VII, 37, 38"],
    ["»» et autres expressions", "» et autres expressions"],
    ["semblables ; Plusieurs", "semblables ; plusieurs"],
    ["passage de.l'Écriture", "passage de l’Écriture"],
    ["(Ib. 30, 6.)", "(Ib. XXX, 6.)"],
    ["parce que son père s’y est opposé ;»", "parce que son père s’y est opposé ; »"],
    ["(Ib. 30, 7-9.)", "(Ib. XXX, 7-9.)"],
    ["''Des eaux faits par la jeune fille peu avant sort mariage", "''Des vœux faits par la jeune fille peu avant son mariage"],
    ["demeurera aussi : « Que si son mari", "demeurera aussi. Que si son mari"],
    // ── p535 ──
    ["c’est-à-dire ; la jugera pure", "c’est-à-dire, la jugera pure"],
    ["L’Écriture par le ensuite", "L’Écriture parle ensuite"],
    ["s’acquitter de leurs vœux « La veuve", "s’acquitter de leurs vœux : « La veuve"],
    ["liée par un veau", "liée par un vœu"],
    ["elle a fait un veau ou une promesse", "elle a fait un vœu ou une promesse"],
    ["ne s’y oppose point tous ses vœux", "ne s’y oppose point : tous ses vœux"],
    ["au jour ou il les a connus", "au jour où il les a connus"],
    ["accomplira son veau", "accomplira son vœu"],
    ["aux veaux de garder", "aux vœux de garder"],
    ["Tel parait être", "Tel paraît être"],
    ["le veau de s’abstenir", "le vœu de s’abstenir"],
    ["soit un veau contre l’âme", "soit un vœu contre l’âme"],
    ["Dans ces sortes de veaux", "Dans ces sortes de vœux"],
    ["mais « que le mari, dit-il", "mais : « Que le mari, dit-il"],
    ["qu’à la femme mais", "qu’à la femme, mais"],
    ["mais ou le mari l’exerce", "mais où le mari l’exerce"],
    ["ses veaux, si la femme", "ses vœux, si la femme"],
    ["ou : de n’user point", "ou de n’user point"],
    ["Mat. 6, 26", "Matt. VI, 26"],
    ["Nom. 29, 7", "Nomb. XXIX, 7"],
    ["1Co. 7, 3-4", "I Cor. VII, 3, 4"],
    // ── p536 ──
    ["nombre des, justifications", "nombre des justifications"],
    ["(Ib. 31, 5-6.)", "(Ib. XXXI, 5, 6.)"],
    ["désigner par la les princes", "désigner par là les princes"],
    ["(Ib. 31, 8.)", "(Ib. XXXI, 8.)"],
    ["Nom. 24, 25.", "Nomb. XXIV, 25."],
    ["« En son « lieu »", "« En son lieu »"],
    ["ne me parait pas", "ne me paraît pas"],
    ["(Ib. 31, 9.)", "(Ib. XXXI, 9.)"],
    ["Prophète « Je vous ôterai", "Prophète : « Je vous ôterai"],
    ["Isa. 3, 1.", "Isaïe, III, 1."],
    ["(Ib 31, 15-16.)", "(Ib. XXXI, 15, 16.)"],
    ["L’Écriture ne lit pas", "L’Écriture ne dit pas"],
    // ── p537 ──
    ["(Ib. 35, 14, 42.)", "(Ib. XXXV, 14, 12.)"],
    ["l’Écriture dit-elle « Vous aurez", "l’Écriture dit-elle : « Vous aurez"],
    ["(Ib. 35, 19, 42.)", "(Ib. XXXV, 19, 12.)"],
  ],
  LABEL_SIC: [],
}
