create table if not exists public.oeuvres_personnelles_segments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  id_oeuvre text not null,
  auteur text,
  titre text not null,
  segment_numero integer not null,
  segment_texte text not null default '',
  statut_controle text not null default 'bon' check (statut_controle in ('bon', 'revoir', 'critique')),
  notes text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, id_oeuvre, segment_numero)
);

create index if not exists idx_oeuvres_personnelles_segments_user_oeuvre
  on public.oeuvres_personnelles_segments(user_id, id_oeuvre, segment_numero);

alter table public.oeuvres_personnelles_segments enable row level security;

drop policy if exists "Lire ses segments personnels" on public.oeuvres_personnelles_segments;
create policy "Lire ses segments personnels"
  on public.oeuvres_personnelles_segments
  for select
  to authenticated
  using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "Ajouter ses segments personnels" on public.oeuvres_personnelles_segments;
create policy "Ajouter ses segments personnels"
  on public.oeuvres_personnelles_segments
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "Modifier ses segments personnels" on public.oeuvres_personnelles_segments;
create policy "Modifier ses segments personnels"
  on public.oeuvres_personnelles_segments
  for update
  to authenticated
  using ((select auth.uid()) = user_id or public.is_admin())
  with check ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "Supprimer ses segments personnels" on public.oeuvres_personnelles_segments;
create policy "Supprimer ses segments personnels"
  on public.oeuvres_personnelles_segments
  for delete
  to authenticated
  using ((select auth.uid()) = user_id or public.is_admin());

grant select, insert, update, delete on public.oeuvres_personnelles_segments to authenticated;
grant usage, select on sequence public.oeuvres_personnelles_segments_id_seq to authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_oeuvres_personnelles_segments_updated_at on public.oeuvres_personnelles_segments;
create trigger trg_oeuvres_personnelles_segments_updated_at
  before update on public.oeuvres_personnelles_segments
  for each row execute function public.set_updated_at();
