-- Migration non destructive pour la page /quiz.
-- À exécuter dans Supabase SQL Editor.

alter table public.versets
  add column if not exists quiz_exclu boolean not null default false,
  add column if not exists quiz_exclusion_raison text;

create table if not exists public.quiz_signalements (
  id bigint generated by default as identity primary key,
  id_verset text not null references public.versets(id_verset) on delete cascade,
  raison text not null,
  commentaire text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.quiz_signalements enable row level security;

drop policy if exists "quiz_signalements_insert_public" on public.quiz_signalements;
create policy "quiz_signalements_insert_public"
on public.quiz_signalements
for insert
to anon, authenticated
with check (true);

drop policy if exists "quiz_signalements_select_admin" on public.quiz_signalements;
create policy "quiz_signalements_select_admin"
on public.quiz_signalements
for select
to authenticated
using (public.is_admin());

drop policy if exists "quiz_signalements_update_admin" on public.quiz_signalements;
create policy "quiz_signalements_update_admin"
on public.quiz_signalements
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "quiz_signalements_delete_admin" on public.quiz_signalements;
create policy "quiz_signalements_delete_admin"
on public.quiz_signalements
for delete
to authenticated
using (public.is_admin());
