name: Temporary textual versions patch

on:
  push:
    paths:
      - '.github/workflows/temporary-textual-versions.yml'

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - run: echo textual-versions-workflow-ok
